### PR TITLE
committers-doc.dot: move myself to alumnii

### PR DESCRIPTION
**Pull request by grahamperrin**
https://cgit.freebsd.org/doc/commit/?id=3cf16c8526c8cd78418b956f4cec78aeed63af9f
was as requested by me.

### CODE REVIEW

**Comment by lwhsu** [comment]
Merged as dbf30052ca44c482d564090f54538cee36be83d0

**Comment by cschuber** [comment]
I think we forgot one thing. The doc commit bit needs to be put into safe-keeping too.

**Comment by grahamperrin** [comment]
Thanks. 

> … doc commit bit needs to be put into safe-keeping …

<https://cgit.freebsd.org/doc/commit/?id=3cf16c8526c8cd78418b956f4cec78aeed63af9f> (2023-08-24): 

>> Safekeep grahamperrin's commit bit per request

There, my username was correct. Thanks, @evilgjb (maybe evil by name, decidedly non-evil by nature). 

----

https://github.com/freebsd/freebsd-doc/commit/0fb13633d5e93eaf7eb563a36145c7b20de7c237 misspelt my username in the commit message, which did not make the resignation situation any happier.

Anyone can make a mistake (as I did, above, with the word _alumni_). Not everyone can correct mistakes. I'm disappointed that my plea to correct the commit message has been ignored. 

To anyone who has a relevant commit bit, and is willing, **please**: 

`git -C /usr/doc rebase --interactive 0fb13633d5e9~`

TIA

**Comment by lwhsu** [comment]
Unfortunately, the commit message, or anything else, in the official is not able to be changed because the consistency reason. Changing the history will cause all the forks and WIPs got divergence. That's a serious and unrecoverable issue.

**Comment by grahamperrin** [comment]
@lwhsu thanks for explaining. Now, I understand that it can't be done.

**Pull request closed without merging**
