### PR TITLE
geom/journal: Fix typos

### PR DESCRIPTION
**Pull request by agiUnderground**
Fixed a few typos.

### CODE REVIEW

**Review by igalic — APPROVED** [review]

**Comment by agiUnderground** [comment]
Hi! Is it normal that PR's are ignored for over a month? I know that my PR is not important; it is not a bugfix, but anyway.

**Comment by bsdimp** [comment]
> Hi! Is it normal that PR's are ignored for over a month? I know that my PR is not important; it is not a bugfix, but anyway.

It's not normal... I usually do a run of these at least once a month... work got busy in October, so I'm behind in landing them. Please accept my apologies for the delay. The change looks perfect as is. About the only thing I can think to ask is there a last name you'd like in your name?

**Comment by agiUnderground** [comment]
> About the only thing I can think to ask is there a last name you'd like in your name?

I don't really care about credits; I just want to make FreeBSD a little bit better. I hope that's okay. Thanks!

**Comment by bsdimp** [comment]
landed. thanks for your contrib and sorry I've been asleep at the wheel... merged!

**Pull request closed without merging**
