### PR TITLE
a bug in initialization of sblock.fs_maxbsize

### PR DESCRIPTION
**Pull request by wy-chung**
sblock.fs_maxbsize is not initialized yet in the else if statement. It should be maxbsize in this else if statement.

### CODE REVIEW

**Review by hselasky — COMMENTED** [review]
Looks good. Do you have a committer for this?

**Comment by wy-chung** [comment]
> Looks good. Do you have a committer for this?

No, I don't have a committer for this .

**Comment by hselasky** [comment]
OK, I'm trying to get a comment from Kirk M. first. Then your patch is ready to go upstream.

**Comment by hselasky** [comment]
Hi,
Your patch has been submitted upstream. This issue can now be closed!
--HPS

**Comment by wy-chung** [comment]
ok :)

**Pull request closed without merging**
