### PR TITLE
Allow user to specify ZFSBOOT_POOL_SIZE for unattended installs.

### PR DESCRIPTION
**Pull request by johnko**
The default is to create a zroot that consumes the whole disk because if used with geli(8) this makes sense.

Without geli(8), I like to keep my data pool separate from my system pool.

This is different than ZFSBOOT_BOOT_POOL_SIZE which is named bootpool.

### CODE REVIEW

**Comment by johnko** [comment]
@allanjude  I've squashed my patch to just this, if you're interested.

Thx.

**Comment by bsdimp** [comment]
Paging @allanjude @devinteske what say you all?

**Comment by devinteske** [comment]
Will have a look tomorrow, thanks

**Comment by tykling** [comment]
@johnko I am working on putting an option to limit zroot pool size in the installer, when using the zfs auto partitioning. Seems like it should be possible to use your code along with a few modifications to the installer. Thoughts?

**Comment by johnko** [comment]
Sorry, I haven't looked at this code in about 2 years, I trust @allanjude would grok it better.

**Comment by johnko** [comment]
@tykling probably, I used these modification at the time (2015) for my installs but I think I skipped the Interactive Installer and had my own wrapper script to do my installs:
- Here's where I downloaded my custom zfsboot: https://github.com/johnko/freebsd-install-script/blob/master/bin/fzg#L591
- Here's where I call `bsdinstall zfsboot`: https://github.com/johnko/freebsd-install-script/blob/master/bin/fzg#L621-L622
- The rest of the wrapper script is just setting up GELI disks and `bsdinstall distfetch`, `checksum`, `distextract`, etc.

**Comment by bsdimp** [comment]
rebased and updated https://reviews.freebsd.org/D30588

**Comment by bsdimp** [comment]
7ef92163ab81 resolves this issue by committing this patch, as reviewed by @allanjude

**Pull request closed without merging**
