### PR TITLE
ports(7): '*-list' targets: Add/fix doc on whether they are recursive

### PR DESCRIPTION
**Pull request by OlCe2**
Align the doc with the current behavior.

### CODE REVIEW

**Comment by bsdimp** [comment]
landed as d0b0bc37a3a5
I think I overlooked this one for some reason...

**Comment by OlCe2** [comment]
Thanks.

**Comment by bsdimp** [comment]
Sure b4dd6e1a2837

**Comment by OlCe2** [comment]
Perfect, thanks.

**Pull request closed without merging**
