### PR TITLE
release: Change vmimage EFI GPT label

### PR DESCRIPTION
**Pull request by jlduran**
This matches the default bsdinstall nomenclature.

PR:		278480

### CODE REVIEW

**Comment by jlduran** [comment]
As a side note, I would like to change the spacing to match the output of `mount -p`, but that is a cosmetic change that can be addressed globally later.

**Comment by bsdimp** [comment]
@cperciva @bapt @emaste @lwhsu @nwhitehorn 
This change looks good to me and my eye, but tagging a few people to see if there's something subtle I'm missing.

**Comment by cperciva** [comment]
LGTM.  I'm 99.9% confident that the divergence is accidental.

**Comment by bsdimp** [comment]
Landed, thanks for your contribution.

**Pull request closed without merging**
