### PR TITLE
uefi(8): Refer to a related manual page

### PR DESCRIPTION
**Pull request by tomhukins**
PR:	265834
Differential Revision: https://reviews.freebsd.org/D39577

### CODE REVIEW

**Comment by concussious** [comment]
I've been working on this for a while, I intended to do more, but since you're working on it now, how do you feel about this?

https://github.com/freebsd/freebsd-src/commit/498506ded2552962d5101ba61ccebf7fc8157076

**Comment by tomhukins** [comment]
> I've been working on this for a while, I intended to do more [0], but since you're working on it now, how do you feel about this [1]?

I don't have a great deal of knowledge about UEFI, but I welcome your efforts to improve FreeBSD's documentation.

In February, I noticed [bug 265834](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265834) and submitted a small patch that would complete the work required to close that bug.  After several rounds of patching, my work remains uncommitted, so I decided to submit a pull request for it.  I've had more luck getting my work committed when I submit pull requests.

**Comment by mhorne** [comment]
Thanks Tom. I grabbed your commit and pushed to `main`. 

You should be able to close this PR, but I cannot.

**Comment by tomhukins** [comment]
Merged to main in f49d6f5.

**Pull request closed without merging**
