### PR TITLE
restore: Fix typo in veriexec man page

### PR DESCRIPTION
**Pull request by hsuan1117**
Name: Jui-Hsuan Chang
Email: hsuan1117@gapp.nthu.edu.tw

Typos corrected:
derrives -> derives

This is from the Advanced UNIX Programming Course (Fall’23) at NTHU.

### CODE REVIEW

**Review by rilysh — CHANGES_REQUESTED** [review]
I think you should add a message (the course) in your commit.
e.g.
```
veriexec(8): Fix typo in man page

Event: Advanced UNIX Programming Course (Fall’23) at NTHU.
```
See https://github.com/freebsd/freebsd-src/pull/951#issuecomment-1869693910

**Comment by hsuan1117** [comment]
Hello @rilysh , I have just modified my commit message, plz take a look.
Thanks a lot !

**Review by rilysh — APPROVED** [review]
Looks good!

**Comment by igalic** [comment]
n.b.: your commit meta data does not match up with what you'd like it to be:

```
Name: Jui-Hsuan Chang
Email: hsuan1117@gapp.nthu.edu.tw
```

vs,

```
From: Hsuan <34859514+hsuan1117@users.noreply.github.com>
```

see, https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

you need to set the commit email in your git cli, then go back rewrite the author: https://stackoverflow.com/questions/750172/how-do-i-change-the-author-and-committer-name-email-for-multiple-commits#1320317

**Comment by hsuan1117** [comment]
@igalic I have modified the author name, thanks for reminding.

**Review by igalic — APPROVED** [review]
👍

**Review by lwhsu — APPROVED** [review]

**Comment by lwhsu** [comment]
Merged as c8e7649b9909edc41bdff6c9f0b720d9e116dcc0

**Pull request closed without merging**
