### PR TITLE
CONTRIBUTING.md: minor changes

### PR DESCRIPTION
**Pull request by WuerfelDev**
- Misspelled GitHub
- angle bracket not escaped correctly
- ~Double white spaces~
- White spaces at EOL

### CODE REVIEW

**Comment by jlduran** [comment]
These are nice fixes, thank you!
Paging @bsdimp or @emaste.
The only thing I would suggest, is leaving the two spaces after the periods, maybe out of nostalgia, or maybe I could say that the CommonMark specification uses two spaces after periods.
It's up to them to decide.

**Comment by bsdimp** [comment]
Two spaces are the one true way.
Too many don't follow the way.
I can go either way, but I always use two spaces.

**Comment by WuerfelDev** [comment]
I reinserted those spaces. Never used double spaces on purpose before but I guess it helps with readability

**Comment by igalic** [comment]
fwiw, in the docs and on the website, we ask people to put one sentence per line.
This makes it easy to read during review, and easy to diff on change, because changes often happen at a sentence level

**Comment by bsdimp** [comment]
> fwiw, in the docs and on the website, we ask people to put one sentence per line. This makes it easy to read during review, and easy to diff on change, because changes often happen at a sentence level

I thought we didn't do that for markdown documents because it messed up the rendering

**Comment by jlduran** [comment]
> fwiw, in the docs and on the website, we ask people to put one sentence per line.
> This makes it easy to read during review, and easy to diff on change, because changes often happen at a sentence level

Some Markdown (in GitHub's case CommonMark) parsers may interpret the the sentence on a new line as a line break.
For example, this sentence will appear on a new line, i.e., it will insert a `<br>` between the two lines, which is almost visually like a new paragraph, it may not be what I originally intended.  I would have wanted it to look like this sentence.

If an empty line in between is used, then a paragraph is rendered.

**Comment by bsdimp** [comment]
OK. One last issue. The author name is listed as
```
Author: WuerfelDev <WuerfelDev@users.noreply.github.com>
```
which is a nonsense email address. Do you have a real email address you'd like me to use? or I could do `Submitted by: github user WuerfelDev` if you like.

**Comment by bsdimp** [comment]
Thanks! Pushed! 
And at the last second, went ahead with the one space patch. I appreciate you reverting it, but I think that it's likely best to go with that trend.

**Pull request closed without merging**
