### PR TITLE
nl(1): Capsicumise the utility

### PR DESCRIPTION
**Pull request by kfv**

### CODE REVIEW

**Review by markjdb — APPROVED** [review]
This looks good to me. I suspect we also want a `caph_cache_catpages()` call in there.

**Comment by oshogbo** [comment]
Yes, we use `err()`, so doing `caph_cache_catpages()` might be useful.

**Comment by kfv** [comment]
Done.

**Comment by oshogbo** [comment]
Done: dfd52321b7beba716fa2bdd4f54e57e9ac806e96

**Pull request closed without merging**
