### PR TITLE
GitHub: Silence clang-12 cross builds

### PR DESCRIPTION
**Pull request by jlduran**
The main idea is to stir a discussion, rather than present this pull request as the actual fix.

Can we just remove clang-12 from the test matrix?

cc/ @jrtc27, @emaste, @bsdjhb (educated guess of reviewers)

### CODE REVIEW

**Comment by bsdimp** [comment]
I think we can just drop clang12 from the mix... unless the change to linux/unistd.h really fixes it, in which case we should do that...

**Comment by lwhsu** [comment]
> I think we can just drop clang12 from the mix... unless the change to linux/unistd.h really fixes it, in which case we should do that...

#678 seems working. BTW, if we're going to drop clang 12 support, we need to update https://docs.freebsd.org/en/articles/committers-guide/#_current_compiler_versions

**Comment by bsdimp** [comment]
> > I think we can just drop clang12 from the mix... unless the change to linux/unistd.h really fixes it, in which case we should do that...
> 
> #678 seems working. BTW, if we're going to drop clang 12 support, we need to update https://docs.freebsd.org/en/articles/committers-guide/#_current_compiler_versions

Yea, I think we should commit this fix, but keep clang12 since we need it still for stable/12 til its EOL. Might as well test it with a recent-ish ubuntu too.

**Comment by jlduran** [comment]
You are right! it should be kept until EOY.

I just tested `ubuntu-latest` + `clang-15` and it works as expected. I'll submit a separate pull request for evaluation, but before that, how should the final cross-build matrix be?:

| OS version    | clang-12 | clang-13 | clang-14 | clang-15 |
|:--------------|:--------:|:--------:|:--------:|:--------:|
| macos-latest  | ✅       | ✅       | ✅       | ✅       |
| ubuntu-latest | ✅       | ✅       | ✅       | ✅       |

**Comment by bsdimp** [comment]
Got the OK from @jrtc27 on IRC, with an appropriate commit message.

**Review by bsdimp — APPROVED** [review]
I'll steal much of the comment to do the push...

**Pull request closed without merging**
