### PR TITLE
typo in contrib/bearssl/src/hash/ghash_pclmul.c

### PR DESCRIPTION
**Pull request by 108062138**
Name: Po-Yu, Wu
Email: poyuwu17@gapp.nthu.edu.tw
[At contrib/bearssl/src/hash/ghash_pclmul.c line79](https://github.com/freebsd/freebsd-src/blob/dbca442414191a43f334435b7910b63cb2777d53/contrib/bearssl/src/hash/ghash_pclmul.c#L79
): shitfting -> shifting

This is from the Advanced UNIX Programming Course (Fall’23) at NTHU.

### CODE REVIEW

**Review by rilysh — APPROVED** [review]

**Comment by rilysh** [comment]
I think BearSSL is directly pulled from its Git repository to FreeBSD. You should report it there, so later it will be synced here. See [contrib](https://www.bearssl.org/contrib.html).

**Comment by bsdimp** [comment]
I agree with @rilysh: please submit this upstream and post a link here. If you need to know where, just ask...

**Comment by 108062138** [comment]
> I agree with @rilysh: please submit this upstream and post a link here. If you need to know where, just ask...

Thx for your reply, there is one more thing I'm confused.
After I contact `BearSSL` and notify the typo(according to `rilysh`), I need post a link. It is the link that confused me. 
Is it about `BearSSL`'s update info?

**Comment by rilysh** [comment]
@108062138 You can send direct patches (in email)

You can either send this patch: https://patch-diff.githubusercontent.com/raw/freebsd/freebsd-src/pull/952.diff
Or directly the line where the typo is: https://www.bearssl.org/gitweb/?p=BearSSL;a=blob;f=src/hash/ghash_pclmul.c;h=a58e7dc02bebcfe855f384d937848d8189b25fc2;hb=HEAD#l79

With some additional context.

**Comment by bsdimp** [comment]
The general answer about what we'd like to document it is 'whatever the upstream offers'. Some do it all by email, in which case just pointing to the thread in their email archives is fine. Others do it by pull request, and those usually have a URL you can share here (and if it is on github, then there's cross-repo tracking of the different issues). These links will help us followup on things in the future.

**Comment by 108062138** [comment]
> The general answer about what we'd like to document it is 'whatever the upstream offers'. Some do it all by email, in which case just pointing to the thread in their email archives is fine. Others do it by pull request, and those usually have a URL you can share here (and if it is on github, then there's cross-repo tracking of the different issues). These links will help us followup on things in the future.

Thx for your detailed reply~~
I just send `bearssl` email to notify them those typo and currently wait for their feedback.

**Comment by bsdimp** [comment]
I'm going to close this, we'll get it with the next bearssl import and don't need to keep it open.

**Pull request closed without merging**
