### PR TITLE
.gitignore: add sys/*/compile

### PR DESCRIPTION
**Pull request by llfw**

### CODE REVIEW

**Review by igalic — APPROVED** [review]
👍

**Comment by emaste** [comment]
Commit message should explain not just "what" but also "why". What produces sys/*/compile files that need to be ignored?

**Comment by llfw** [comment]
improved the commit message, no functional changes

**Comment by jrtc27** [comment]
> Files in sys/*/compile are created when compiling the kernel with
> config(8).  They are never source files and should never be committed to
> source control, so list this entire directory in .gitignore.

Do we actually support people using config(8) directly to build kernels? I'm inclined to say anything other than a buildkernel in a tree that's had kernel-toolchain (whether directly or via buildworld / kernel-toolchains / etc) run is unsupported. For one you won't have any tools bootstrapped that you might need.

**Comment by emaste** [comment]
I think I haven't used the config-method in a decade or two, and it may well be unsupported, but I wouldn't object to having entries in .gitignore

**Comment by bsdimp** [comment]
I use the config method from time to time. It still works, is still useful and i like this change.

**Comment by bsdimp** [comment]
Tiny tweak to the commit message. 93a25ac9f4c0
Not sure how to credit @emaste or @jrtc27 on this since they didn't explicitly say OK (though the thumbs up might be?)

**Pull request closed without merging**
