### PR TITLE
Standardize more C string functions

### PR DESCRIPTION
**Pull request by gAlfonso-bit**

### CODE REVIEW

**Comment by bsdimp** [comment]
This is missing the updates to the memccpy and strtok man pages.

**Comment by gAlfonso-bit** [comment]
I should have drafted this PR

**Comment by bsdimp** [comment]
The commit messages need to be more descriptive as well. Each commit should describe what changed and why.

For example "Add __restrict to memccpy args, per The Open Group Base Specifications Issue 7, 2018 edition"

**Comment by bsdimp** [comment]
I'll review again when you're ready...

**Pull request closed without merging**
