### PR TITLE
D37248 and D37250

### PR DESCRIPTION
**Pull request by jlduran**
Commits for D37248 and D37250.

### CODE REVIEW

**Comment by asomers** [comment]
There's no need to open a Github PR for code that's already been reviewed on Phabricator.  It's redundant.  Just ask the Phabricator reviewer to commit it for you.

**Comment by markjdb** [comment]
> There's no need to open a Github PR for code that's already been reviewed on Phabricator. It's redundant. Just ask the Phabricator reviewer to commit it for you.

I asked for it - fetching raw patches from phabricator and amending them with the right author metadata and fixing the commit log mangling is rather tedious.

**Comment by asomers** [comment]
> I asked for it - fetching raw patches from phabricator and amending them with the right author metadata and fixing the commit log mangling is rather tedious.

Interesting.  Do you have that scripted?

**Comment by jlduran** [comment]
> Do you have that scripted?

Not scripted, only documented here: https://docs.freebsd.org/en/articles/committers-guide/#github-pull-land. Not sure if it helps.

**Comment by markjdb** [comment]
I don't have it scripted, there's still some manual effort involved. I use the github CLI client (`gh`) to fetch pull requests into my local repo, which is a bit easier than what's documented in the handbook.

**Comment by bsdimp** [comment]
Yea, I do the following (assuming my repo is on main):
```
% git fetch github
% git cherry-pick main..github/pull/$X/head
# test here
% git pull --rebase
% git push --push-option=confirm-author
```
This also lets me cherry-pick only some of the commits on a branch in case that's needed. We likely should document something closer to that because the current docs are kinda verbose.

**Pull request closed without merging**
