### PR TITLE
Use recent clang releases in github actions

### PR DESCRIPTION
**Pull request by zxombie**

### CODE REVIEW

**Comment by jlduran** [comment]
Nice!
https://docs.freebsd.org/en/articles/committers-guide/#_current_compiler_versions might also need an update.

**Comment by bsdimp** [comment]
@brooksdavis @jrtc27 Comments on this? @emaste

**Comment by jlduran** [comment]
Maybe I should try to rekindle #681?

**Review by emaste — APPROVED** [review]

**Review by bsdjhb — APPROVED** [review]

**Comment by brooksdavis** [comment]
We've still got at least one Ubuntu 20.04 runner for CheriBSD builds, but could probably get it upgraded without too much trouble. Not sure were the CL stands on deployed systems. I think oldest clang we care about is 14 for Morello. We've got a completed merge request https://git.morello-project.org/morello/llvm-project/-/merge_requests/293 to move to 15, but it's stalled and there's at least one derivative project that may not have caught up.

**Pull request closed without merging**
