### PR TITLE
netstat.1: Clarify -d argument

### PR DESCRIPTION
**Pull request by bramton**
The number of dropped input packets are always shown, the `-d` flag adds the dropped output packets to the output.

### CODE REVIEW

**Comment by concussious** [comment]
I like this!
Please use `git commit --amend` to change your commit message to something similar to below. The key issues:
1. Your PR title is perfect for the commit. First comes the thing changed, then a colon. This helps people scrolling through the log identify what's interesting to them.
2. Message body, optionally explaining what's going on to someone unfamiliar with the topic.
3. Without MFC trailer, this will not go into production until freebsd 15.
4. PR trailer helps us produce data on how useful github is to the project.
`````
netstat.1: Clearified -d argument

The number of dropped input packets are always shown,
the -d flag adds the dropped output packets to the output.

MFC after: 3 days
Pull Request: https://github.com/freebsd/freebsd-src/pull/1332
`````
If this was helpful to you, you can also add another trailer `Reviewed by: Alexander Ziaee` to your commit message to show that I'm trying to be helpful.
Thanks!

**Comment by bramton** [comment]
Thanks for the feedback! I have updated the commit message accordingly.

**Comment by concussious** [comment]
Maybe `netstat.1: -d shows dropped "output" packets`? Sorry I didn't think of that initially.

**Comment by bramton** [comment]
I think I will stick to the original commit title, imho it is less confusing. I did fix a typo though, clearify->clarify.

**Review by concussious — APPROVED** [review]

**Review by bsdimp — APPROVED** [review]

**Pull request merged**
