### PR TITLE
hda pin fixes for realtek ALC269

### PR DESCRIPTION
**Pull request by kstaring**
The Linux ALC269-specific pin patches are ported to FreeBSD in this patch. The array in the Linux source containing the ALC269 patches also contains a lot of patches for other ALCXXX chipsets. These were ignored in the porting process for this pull request. They'll be ported in their respective hda_pin_fixes_realtek_alcXXX branch when I come around to port them.
This patch also includes the patches from the ALC880 and ALC260 & ALC268 pull requests.

### CODE REVIEW

**Comment by kstaring** [comment]
(Again, if a different kind of method is desired to submit these patches, or there are suggestions for a better solution to provide pin patches, please say so ;-) )

**Comment by vangyzen** [comment]
Thanks for all your work on this!  I would like to commit your changes, but I don't have much spare time right now.  I'm also hesitant because I don't really know anything about this driver, so I would not be able to help triage or fix any regressions, which is an essential responsibility of the committer.

Submitting patches via pull requests is fine.  Plenty of FreeBSD committers are familiar enough with github to handle them.

**Comment by kstaring** [comment]
Thanks for your response! I was distracted for a couple of days-- there's a lot more patches to go in fact.. Your concerns are of course very understandable; it's a new structure and a lot of new stuff. I hope someone with knowledge of the snd_hda driver can look at it.
Later today I'll ask freebsd-hackers to look at the my [hda_pin_fixes_realtek](https://github.com/kstaring/freebsd/tree/hda_pin_fixes_realtek) branch, I believe there was a thread about audio support not long ago.

**Comment by kstaring** [comment]
(PS, about possible regressions; mostly it's additions in the pin_patch_realtek.h struct-- removing the corresponding entry from the struct, for which one will only need to know the vendor and model of the machine experiencing the regression, is enough to at least get back previous behaviour. Still, having an snd_hda-experienced eye on the code would be ideal!)

**Comment by bsdimp** [comment]
I've taken all these pull requests, squashed them and forward ported them to -current. https://reviews.freebsd.org/D30619 is the review. As such, I'm going to close all these here.

**Comment by bsdimp** [comment]
I've taken all these pull requests, squashed them and forward ported them to -current. https://reviews.freebsd.org/D30619 is the review. As such, I'm going to close all these here.

**Pull request closed without merging**
