### PR TITLE
.github: Restrict permissions on cross-build jobs.

### PR DESCRIPTION
**Pull request by bsdjhb**

### CODE REVIEW

**Comment by bsdjhb** [comment]
Creating a pull request for testing.

**Comment by bsdjhb** [comment]
@sashashura, would you be willing to send me a name and e-mail address to use as the author of this commit for merging into FreeBSD?

**Comment by bsdimp** [comment]
Can this be closed or landed @bsdjhb

**Comment by bsdjhb** [comment]
Committed in aca7ff471acffb59f0f9e2cc4de6363872444fcc.

**Pull request closed without merging**
