### PR TITLE
package: move cron into its own package

### PR DESCRIPTION
**Pull request by llfw**
this allows to use functionality of cron (periodic, etc.) without having to install huge FreeBSD-utilities package. 

cc @evadot, @bapt

### CODE REVIEW

**Comment by igalic** [comment]
@dfr might also interest you

**Comment by bsdimp** [comment]
@bapt, @evadot please review...

This one seems like it could go either way to me, but I lean slightly to 'cron is big enough to be its own thing' but I could easily see that it is really just another util.

**Comment by evadot** [comment]
Yeah it's good for me.

**Comment by bsdimp** [comment]
looks good... last call...

**Review by igalic — APPROVED** [review]
👍

**Comment by bsdimp** [comment]
merged

**Pull request closed without merging**
