### PR TITLE
Optimize bitwise operations in pfctl

### PR DESCRIPTION
**Pull request by AtariDreams**
We can use compiler intrinsics to do this instead of doing it manually.

### CODE REVIEW

**Comment by AtariDreams** [comment]
@bsdimp Thoughts?

**Comment by igalic** [comment]
cc @kprovost

**Comment by bsdimp** [comment]
that's a lot of code churn that takes some concentration to see if they are the same.
What's the measured improvement in speed?

**Comment by bsdjhb** [comment]
This is too noisy a diff.  Most if it is converting signed to unsigned.  For the code in question, it would likely be easier to read/understand if it just used builtin_popcount or bitcount32 from <sys/bitcount.h>:

```
     return (bitcount32(mask[0]) + bitcount32(mask[1]) + bitcount32(mask[2]) + bitcount32(mask[3]));
```

or the like.  That said, it's also not performance critical, so readability is more important than speed here.

**Comment by bsdimp** [comment]
Since this isn't fixing a specific bug, and there's no demonstrated performance win, I'm going to close it. We don't have the time to process changes like this and there's a high risk of regression.

**Pull request closed without merging**
