### PR TITLE
Prefer returning from main over calling exit in main

### PR DESCRIPTION
**Pull request by AtariDreams**
This is redundant otherwise.

### CODE REVIEW

**Comment by bsdimp** [comment]
Why? Seems like a lot of churn for no gain.

**Comment by AtariDreams** [comment]
> Why? Seems like a lot of churn for no gain.

Gain in terms of, less function calls to do, as well as less confusion for the compiler. Yeah I agree not every instance should be changed, but exit(0) at least in main makes less sense than return 0;

**Comment by bsdimp** [comment]
Any compier that doesn't know exit doesn't return is worthless. We annotate exit for exactly this reason.

I'm strongly inclined to say "no" here...

**Comment by delphij** [comment]
> > Why? Seems like a lot of churn for no gain.
> 
> Gain in terms of, less function calls to do, as well as less confusion for the compiler. Yeah I agree not every instance should be changed, but exit(0) at least in main makes less sense than return 0;

`exit()` is always called regardless if one chooses to `return()` in `main()` or not (see `__libc_start1` in `lib/libc/csu/libc_start1.c` for details).  However, except for a few special cases (for instance, `main()` is called by a different caller, for example when a command is also used as built-in of `sh(1)` where it's desirable to run the command within the same process), calling `exit()` may actually be intentional, and not doing so could confuse a dynamic memory analyzer.

For example, if one allocates memory in `main()` and use an on-stack pointer to reference the memory block, calling `exit()` is slightly different from `return` because for the latter the stack frame would be gone and the memory is leaked, and for the `exit()` case no `free()` is needed (and they shouldn't be used in these cases).

**Comment by emaste** [comment]
@delphij gives a good explanation that provides justification for why a change like this shouldn't be done as a global sweep. If we are doing to make changes like this they should be done on a case-by-case basis and will need to confirm correctness and that it's an improvement in readability.

**Pull request closed without merging**
