### PR TITLE
Update option_survey.sh

### PR DESCRIPTION
**Pull request by michaeldexter**
Increase image size from 4G to 5G to accommodate current OS. Tested on 14.1-BETA2.

### CODE REVIEW

**Comment by emaste** [comment]
commit subject line should include a brief description of the change, so include e.g. `increase image size` or `increase image size to 5GB`. You can update the commit and push the update to the pull request (or if I'm going to land this I can just make the change).

**Comment by michaeldexter** [comment]
By the way... syncing this with the VM-IMAGE size in /usr/src/release would solve this in the long term as that code gets much more attention than the build option survey.

**Comment by michaeldexter** [comment]
FYI, builds reach 85% or so.

**Comment by michaeldexter** [comment]
51 builds are complete, for those who celebrate: 

https://callfortesting.org/results/14.1-BETA2/

**Pull request merged**
