### PR TITLE
USB/U3G: Added Panasonic CF-F9 GOBI 3G modem to U3G module.

### PR DESCRIPTION
**Pull request by cederom**
Note: GOBI modems require QDL firmware to be uploaded with gobi_loader:
https://github.com/kicer/gobi_loader
https://github.com/cederom/gobi_loader

Signed-off-by: CeDeROM Tomasz CEDRO <tomek@cedro.info>

### CODE REVIEW

**Comment by cederom** [comment]
If you need GOBI2000 firmware for Panasonic ToughBook CF-F9 and HP EliteBook 2740p I have added them to https://github.com/cederom/gobi_loader :-)

**Comment by grimreaper** [comment]
Has anyone looked at this since its submission?

**Comment by hselasky** [comment]
Hi,

The u3g.conf should not be in the kernel. Other parts look fine. Please make a bugzilla PR at FreeBSD.org.

--HPS

**Comment by cederom** [comment]
Thanks @hselasky :-) Where should I put the example conf? Commit works fine on my rugged laptop :-)

**Comment by hselasky** [comment]
Isn't there a gobi_loader port where it should be put?

**Comment by mzary** [comment]
Unfortunately, there is not such a port in the ports tree yet. The original gobi_loader builds seamlessly, almost without patching so I am using it for years but it would be nice if we have such a port available as net/gobi_loader.

**Comment by cederom** [comment]
Here are sources of GOBI LOADER that I use on FreeBSD :-)

https://github.com/cederom/gobi_loader

For that you also need dedicated firmwares for a modem that can be extracted from windows drivers package :-)

**Comment by mzary** [comment]
I have been also using for about 5 years this fork: https://github.com/kjopek/gobi_loader of https://github.com/kicer/gobi_loader project. To make it even worse I have lately created my own fork to trim unneeded binaries for preparation of FreeBSD port sysutils/gobi_loader. It's under review: https://reviews.freebsd.org/D22938. Please feel free to comment, test, check, contribute or complain on this proposal.

**Comment by bsdimp** [comment]
I've rebased the kernel bits (but didn't include a reviewed by hps since I just noticed he'd said OK). I'm closing this as all committable parts are in the tree. I've sent queries for the port and will followup.

**Pull request closed without merging**
