### PR TITLE
Perfer sys/cdefs.h __unreachable over the builtin

### PR DESCRIPTION
**Pull request by collinfunk**
The __builtin_unreachable macro provided by Clang and GCC is a hint to the compiler used for optimization. The programs work fine even if the compiler doesn't support it. The sys/cdefs.h has had __unreachable for 9 years (commit 732b31de5d9244bd1cc98192e09ee1881e9f55e9). It expands to the builtin if it is available. In the rare case that it is unsupported it expands to a null statement so compilation does not fail.

### CODE REVIEW

**Comment by collinfunk** [comment]
@bsdimp @emaste ISO C 23 N2826 adds the function-like macro unreachable() to stddef.h. Can I submit a separate patch proposing that change? I'm not sure if it is something left up to the GCC/Clang people to include with their headers though...

**Review by igalic — CHANGES_REQUESTED** [review]
this needs one commit per subsystem.
you're touching completely unrelated parts of the system here

**Comment by collinfunk** [comment]
> this needs one commit per subsystem.

Oops, my bad. Split into three commits, one for each program.

**Review by igalic — APPROVED** [review]
👍🏻

**Comment by bsdimp** [comment]
Landed this... go ahead and start to implement the c23 defined macro if you can do it w/o problems on older C compilers.

**Comment by bsdimp** [comment]
OK, automation still bad, but I caught it this time.

**Pull request closed without merging**
