### PR TITLE
Update if_ether.c

### PR DESCRIPTION
**Pull request by orange30**
Free memory before return from arprequest_internal.

### CODE REVIEW

**Comment by bsdimp** [comment]
This looks sane to me.

**Comment by orange30** [comment]
I am reading the code of arp, when I read the function in_arpinput, I find it also need free mbuf before return. @bsdimp  Please help to check it, thanks.

**Comment by markjdb** [comment]
Looks ok. It appears that in_arpinput() has the same bug: if arp_fillheader() fails, it returns without a `goto drop`.

**Comment by orange30** [comment]
See th pr #534 please.

**Pull request closed without merging**
