### PR TITLE
Add Support for Huawei 4G Modem devices (2022)

### PR DESCRIPTION
**Pull request by paepckehh**
# Add support for Huawei 4G Modem devices (2022).
* add new Huawei 4G E3372_NCM (0x1505) 
* add new Huawei 4G E3372v153_NCM (0x155f)
* add new Huawei 4G E5573Cs322_NCM (0x155e)
* add new Huawei 4G E5573Cs322_ECM (0x14db)
* add new Huawei 4G E5573Cs322_ACM (0x1442)
* remove Huawei 3G E3131 (E3131_INIT): 
	- frees up 0x1505/0x14fe shared IDs => product is EOL
	- 3G networks are shutdown/scheduled 
	- E3131 devices will still work the same via eject2 
	- new 4G devices will switch & report correctly now

* Default all devices to simple NCM mode and get a consistent and reliable behavior. No matter what firmware version and provider mix are involved.

* Fixing the root cause and bundle a working firmware for ECM is not possible. Huawei sells the same hardware, different (crippled) firmware versions at different price points in different markets as strategy.

### CODE REVIEW

**Comment by mjguzik** [comment]
@hselasky

**Comment by hselasky** [comment]
I'm watching, but currently a bit busy.

**Comment by paepckehh** [comment]
If the re-purpose of the E3131 (0x1505/0x14fe) recycled USB IDs (big thank you @Huawei for the mess) is a show stopper, I can prep a different patch, without touching any legacy.

**Comment by bsdimp** [comment]
I went to merge this, but there's a merge commit at the front of the stack.
In the future, please rebase your changes forward, rather than merging them forward.
(I was able to do this with this branch with git rebase -i main)

I don't understand this commit message, though:
```
    add support for Huawei E5573Cs322
    
    Switch the now added E5573Cs322_ECM (0x14db) as well per default to NCM.
    
    Rationale:
    Even the bigger SOC shows under complex load in ECM (double-nat) mode
    the same performance drop from 25Mbit to 2Mbit Line Speed, similar to E3372h.
    Reason: Thermal problems (reported via serial debug interface in ACM Mode)
    after 2-3 minutes load.
```

I'm not sure what's being explained here. There's a problem, I understand, but
I don't know if this fixes the problem or if it switches the default to avoid the
problem.

**Comment by bsdimp** [comment]
> If the re-purpose of the E3131 (0x1505/0x14fe) recycled USB IDs (big thank you @Huawei for the mess) is a show stopper, I can prep a different patch, without touching any legacy.

Unless somebody says something, I think this is fine. The fallback for these old devices that won't work anyway is acceptable, imho. It's a mess, but more of a theoretical one...

**Comment by paepckehh** [comment]
> I went to merge this, but there's a merge commit at the front of the stack. In the future, please rebase your changes forward, rather than merging them forward. (I was able to rebase this branch with git rebase -i main)

Yes, sorry for that! That is a result of the github/split-brain-interface. I already pitched sucessfully for a phabricator account to make it more convenient to review, discuss, approve.

**Comment by paepckehh** [comment]
> I'm not sure what's being explained here. There's a problem, I understand, but I don't know if this fixes the problem or if it switches the default to avoid the problem.

* With this patch we default all devices to simple NCM mode to avoid the problem and get a consistent reliable behavior. No matter what firmware version and provider mix are involved.

* Fix the root cause and bundle a working firmware is out of reach because Huawei sells the same hardware, different (crippled) firmware versions at different price points in different markets as strategy.

**Comment by bsdimp** [comment]
> > I'm not sure what's being explained here. There's a problem, I understand, but I don't know if this fixes the problem or if it switches the default to avoid the problem.
> 
>     * With this patch we default all devices to simple NCM mode to avoid the problem and get a consistent reliable behavior. No matter what firmware version and provider mix are involved.
> 
>     * Fix the root cause and bundle a working firmware is out of reach because Huawei sells the same hardware, different (crippled) firmware versions at different price points in different markets as strategy.

oh, that makes perfect sense now. Can you adjust the commit message with this explanation? I think that's all that's keeping me from committing. the rest looks good.

**Comment by bsdimp** [comment]
Can I get a better author name than the anonymous github address please?

**Comment by bsdimp** [comment]
I've pulled these changes down locally, and have squashed some together and split the usbdevs change. The squashed commits are logical steps, each of which compiles. The split for the usbdevs was so we can remove the old IDs after the last reference in the code to them is gone. I've reworded the commit messages a little as a result. All that remains is a good author name for these commits.

**Comment by paepckehh** [comment]
https://reviews.freebsd.org/D38383

> I've pulled these changes down locally, and have squashed some together ...

Yes, sorry! I have preped (almost) the same herefor you:
https://reviews.freebsd.org/D38383

Im not that fast (the github webinterface is very restricted in JS less restriced mode and my native git mirror / workplace is currently on a  arm32/rpi2 fbsd cluster via a slow mobile/metered link :)

**Comment by paepckehh** [comment]
> All that remains is a good author name for these commits.

Michael Paecke (me@paepcke.de)

**Comment by bsdimp** [comment]
Thanks for the phabricator review.
   https://github.com/bsdimp/freebsd/pull/new/PR-633
is my working tree. Please approve that either here or there and I'll push one we're both happy.

**Comment by paepckehh** [comment]
> https://github.com/bsdimp/freebsd/pull/new/PR-633 
LGTM! Perfect! 

I will prep a quk fix for the man page in a second.

(Needs a bigger rewrite to track latest changes to explain use of NCM/ECM modes including examples in the next days. )

**Comment by bsdimp** [comment]
ok. I'll push this and keep an eye out for a man page followup.

**Comment by bsdimp** [comment]
pushed upstream as 848ac8451b08d09a81de7bac8ff8fbe0d35df8cb

**Comment by bsdimp** [comment]
oh, I saw the new man page after I pushed... no worries, I pushed. I had to update the .Dd of the file and I changed 3G to 3G and 4G in a couple of places.

**Comment by snail59** [comment]
Hello @paepckehh and @bsdimp.
I wanted to let you know that commit [1997d3a](https://github.com/freebsd/freebsd-src/commit/1997d3a4a9f20a846cf762306fd5193526a1d603) seems to cause some huawei E3372 to not work anymore.
My model is a 3372h-153 (so hilink) but was flashed with a stick firmware.
Previously to this commit, I got /dev/cuaU0, /dev/ttyU0 and their respective .init and .lock files. They do not appear anymore.

Tell me if this is not the right place or if you would like more information.

**Comment by paepckehh** [comment]
review for docu updates for docs are up now, but review / push is pending:

https://reviews.freebsd.org/D38404

**Comment by snail59** [comment]
I have always had to do send commands to u3g.
The documentation you pointed to says echo '`AT^NDISUP=1,1,"internet"' > /dev/lte'`; I was sending this exact command to /dev/cuaU0.
My problem is that /dev/cuaU0 does not exist anymore and that /dev/lte does not exist either.

**Comment by paepckehh** [comment]
If still fails after processing this msg, pls post:

> sysctl dev.u3g
> sysctl dev.cdce 
> ls -la /dev/cuaU* 

You will discover some more ports and a bunch of new possibilities (debugports etc.)  there now. You need to address the NDISUP to /dev/cuaU0.0 

But this (still) changes from system to system and even from boot (order) to boot. Thats why I used /dev/lte already as generic token in the docs. 

If this first series of patches works, I will provide some more that building a stable interface via /dev/lte instead of the generic variable  cuaU*.* targets, so we can make this usable via a simple single line  rc.conf entry for everyone.

**Comment by snail59** [comment]
**1. on last commit**

- `sysctl dev.u3g`

sysctl: unknown oid 'dev.u3g'

- `sysctl dev.cdce`

dev.cdce.0.%parent: uhub2
dev.cdce.0.%pnpinfo: vendor=0x12d1 product=0x1506 devclass=0x00 devsubclass=0x00 devproto=0x00 sernum="" release=0x0102 mode=host intclass=0xff intsubclass=0x03 intprotocol=0x16
dev.cdce.0.%location: bus=1 hubaddr=2 port=3 devaddr=4 interface=1 ugen=ugen1.4
dev.cdce.0.%driver: cdce
dev.cdce.0.%desc: NCM Network Control Model
dev.cdce.%parent:

- `ls -la /dev/cuaU*`

ls: /dev/cuaU*: No such file or directory

- `sysctl -a | grep -i u3g`

 ==> nothing in output

- `ifconfig ue0`

ue0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80000<LINKSTATE>
        ether 2a:0a:ed:ii:ed:00
        media: Ethernet autoselect
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

**2. when  reseting to commit previous 1997d3a**

`git reset --hard 1997d3a4a9f20a846cf762306fd5193526a1d603^1`

- `sysctl dev.u3g`
dev.u3g.0.ttyports: 1
dev.u3g.0.ttyname: U0
dev.u3g.0.%parent: uhub2
dev.u3g.0.%pnpinfo: vendor=0x12d1 product=0x1506 devclass=0x00 devsubclass=0x00 devproto=0x00 sernum="" release=0x0102 mode=host intclass=0xff intsubclass=0x03 intprotocol=0x12 ttyname=U0 ttyports=1
dev.u3g.0.%location: bus=1 hubaddr=2 port=3 devaddr=4 interface=0 ugen=ugen1.4
dev.u3g.0.%driver: u3g
dev.u3g.0.%desc: HUAWEIMOBILE HUAWEIMOBILE, class 0/0, rev 2.10/1.02, addr 3
dev.u3g.%parent: 
- `sysctl dev.cdce`
dev.cdce.0.%parent: uhub2
dev.cdce.0.%pnpinfo: vendor=0x12d1 product=0x1506 devclass=0x00 devsubclass=0x00 devproto=0x00 sernum="" release=0x0102 mode=host intclass=0xff intsubclass=0x03 intprotocol=0x16
dev.cdce.0.%location: bus=1 hubaddr=2 port=3 devaddr=4 interface=1 ugen=ugen1.4
dev.cdce.0.%driver: cdce
dev.cdce.0.%desc: NCM Network Control Model
dev.cdce.%parent:
-  `ls -la /dev/cuaU*`
crw-rw----  1 uucp  dialer  0x78 Feb  6 21:36 /dev/cuaU0
crw-rw----  1 uucp  dialer  0x79 Feb  6 21:36 /dev/cuaU0.init
crw-rw----  1 uucp  dialer  0x7a Feb  6 21:36 /dev/cuaU0.lock
- `sysctl -a | grep -i u3g`
u3g0 on uhub2
u3g0: <HUAWEIMOBILE HUAWEIMOBILE, class 0/0, rev 2.10/1.02, addr 3> on usbus1
u3g0: Found 1 port.
dev.u3g.0.ttyports: 1
dev.u3g.0.ttyname: U0
dev.u3g.0.%parent: uhub2
dev.u3g.0.%pnpinfo: vendor=0x12d1 product=0x1506 devclass=0x00 devsubclass=0x00 devproto=0x00 sernum="" release=0x0102 mode=host intclass=0xff intsubclass=0x03 intprotocol=0x12 ttyname=U0 ttyports=1
dev.u3g.0.%location: bus=1 hubaddr=2 port=3 devaddr=4 interface=0 ugen=ugen1.4
dev.u3g.0.%driver: u3g
dev.u3g.0.%desc: HUAWEIMOBILE HUAWEIMOBILE, class 0/0, rev 2.10/1.02, addr 3
dev.u3g.%parent:
 - ìfconfig ue0`
 ue0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=80000<LINKSTATE>
        ether 2a:0a:ed:ii:ed:00
        inet 10.XX.YY.ZZ netmask 0xffffffc0 broadcast 10.AA.BB.CC
        fib: 1
        media: Ethernet autoselect
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

**Comment by paepckehh** [comment]
You need the u3g kernel module present, as stated in new cdce.4 man page  ([D38404](https://reviews.freebsd.org/D38404))
```shell
sysctl dev.u3g
```
should at least reproduce an empty node if present. 
Can you try 
```shell 
kldload -v u3g
```
before plugging the device.

Do you use a generic or custom kernel? Arch/Plattform?
Do you load the cdce/u3g manually before?

**Comment by snail59** [comment]
kldload -v u3g
kldload: can't load u3g: module already loaded or in kernel

I can confirm that it is built in kernel; here is an extract of my kernel config
```
# huawei 3372h-153 (needs miibus)
device          miibus # MII bus support
device          u3g    # serial port of modem (/dev/cuaU0)
device          cdce   # ncm card
```

**Comment by paepckehh** [comment]
In general, to make u3g work, you need to add 
```shell
device ucom
```
I updated [D38404](https://reviews.freebsd.org/D38404) to make this more explicit in UPDATING as well.

**Comment by snail59** [comment]
I may have found the problem, let me test/check.

**Comment by snail59** [comment]
This did the trick for me:
```
diff --git a/sys/dev/usb/serial/u3g.c b/sys/dev/usb/serial/u3g.c
index 9554f30fcfdf..71918407a1f1 100644
--- a/sys/dev/usb/serial/u3g.c
+++ b/sys/dev/usb/serial/u3g.c
@@ -343,6 +343,7 @@ static const STRUCT_USB_HOST_ID u3g_devs[] = {
        U3G_DEV(HUAWEI, E3272_INIT, U3GINIT_HUAWEISCSI2),
        U3G_DEV(HUAWEI, E3272, 0),
        U3G_DEV(HUAWEI, E3372_INIT, U3GINIT_HUAWEISCSI3),
+       U3G_DEV(HUAWEI, E3372_NCM, 0),
        U3G_DEV(HUAWEI, E3372v153_INIT, U3GINIT_HUAWEISCSI2),
        U3G_DEV(HUAWEI, E3372v153_NCM, 0),
        U3G_DEV(HUAWEI, E5573Cs322_NCM, 0),
```

Does this seem ok to you ?

**Comment by paepckehh** [comment]
Yes, absolute, I see then you have a E3372**h** ?
(the old full retail version, that still had a working SD card slot!?)

```shell 
product HUAWEI E3372_INIT	0x1f01  LTE modem initial
``` 

that ends up switched as 

```shell  
product HUAWEI E3372_NCM	0x1506  LTE modem in NCM mode
``` 

Or is your device reporting direct (native) as 0x1506 ?

I had over the years a lot of different hw/sw versions to test, not all working anymore and it seems I totally overlooked this combination in the u3g table. Great find! Thank you! 

I you want I can add this to the still pending [D38404](https://reviews.freebsd.org/D38404) with your real 
name or alias, as you want as (bug) reporter.

**Comment by snail59** [comment]
> Yes, absolute, seems you have a E3372h ? 

yes I do; but I flashed it from a hilink to a stick firmware.
> The old full retail version, that still had a working SD card slot!?

You are right, I checked and there is indeed an SD card slot. I had totally forgotten about it !!
 > Or is there a device reporting direct (native) as 0x1506 ?

I don't know how to verify this but would be glad to give you the information if you need it and if tell me how to retrieve it.
> this tool to find out more: [lteinfo](https://github.com/paepckehh/lteinfo)

I tried your tool but:
`go/bin/lteinfo /dev/cuaU0 (or lteinfo alone)`
```
### DEVICE ERROR: lte device -> /dev/lte0 not ready! Waiting for device ... 
### DEVICE ERROR: lte device -> /dev/lte0 not ready! Waiting for device ...
```
I have maybe misused it.
> I you want I can add this to the still pending [D38404](https://reviews.freebsd.org/D38404) with your real
name or alias, as you want as (bug) reporter.

Yes, I would be proud to have my name related to FreeBSD :-D. 
I emailed you my name at the address you gave to bsdimp. Tell me if you did not receive it.

**Comment by paepckehh** [comment]
So you did already the switch (intention of this patchset) from ECM to NCM mode via a custom firmware. Ok, thats clever :) 

[D38404](https://reviews.freebsd.org/D38404) is updated with the bugfix and you as reporter.

**Pull request closed without merging**
