### PR TITLE
usb/u3g driver, add support for Quectel EM05

### PR DESCRIPTION
**Pull request by yjqg6666**
Add USB driver support for Quectel EM05. Tested and works like a charm on ppp.

### CODE REVIEW

**Comment by hselasky** [comment]
Should be merged now. Please close!

**Comment by yjqg6666** [comment]
@hselasky Would this patch MFC/back-port to Stable/13 ?

**Comment by hselasky** [comment]
Yes, see:

https://cgit.freebsd.org/src/commit/?id=9e89269ee7e5f31aa60ae8c645821d4ca08f5ae6

--HPS

**Comment by yjqg6666** [comment]
Cool！ I would test it later on the latest commit. It works on stable/13 with up-to-yesterday commits and. this patch.

**Pull request closed without merging**
