### PR TITLE
WIP: Facilitate the update of blacklistd (blocklistd)

### PR DESCRIPTION
**Pull request by jlduran**
@emaste: I hope this can actually help facilitate the updating of [zoulasc/blocklistd](https://github.com/zoulasc/blocklist), as we can clearly see where we are lagging.

The first commit, entitled "REMOVE", is just a `FreeBSD-update` file with the instructions to replicate the procedure used.

The second commit is the actual import.

~~The third commit is what we currently have that upstream doesn't. It looks like it should _just work_ on NetBSD as well, but I have yet to test it.~~

# TODO

### Questions

- [x] Is ipf currently supported? (Rekindle [jlduran/blacklistd-integration-tests](https://github.com/jlduran/blacklistd-integration-tests))
  - [ ] For `ipf(8)`, FreeBSD uses `/etc/ipf.rules`, NetBSD uses `/etc/ipf.conf`. `blacklistd-helper` changed the _firewall detection mechanism_ to `/etc/ipfilter.conf`.
- [x] Should we add `ipf(8)` and `ipfw(8)` as well to `blacklistd.8` ~~(currently we are doing `s/npfctl/pfctl/`)~~?
- [x] Should we change the rc script to `# REQUIRE: ipfilter ipfw pf`?

### Pending

- [x] Check if we can upstream https://github.com/freebsd/freebsd-src/commit/549f31e4590e97c7b9ee771a24fd2c84198f0dd8

### CODE REVIEW

**Comment by emaste** [comment]
I am comparing contrib/blacklist/ with NetBSD's external/bsd/blacklist at 03c74c04f277. Current state:
```
diff -pur --exclude="*.diff" -I '\$NetBSD.*\$' contrib/blacklist/ ~/src/netbsd-src/external/bsd/blacklist/ | diffstat
 blacklist/bin/blacklistctl.c        |    3 
 blacklist/bin/blacklistd.8          |    8 -
 blacklist/bin/blacklistd.c          |   33 ++----
 blacklist/bin/blacklistd.conf.5     |    2 
 blacklist/bin/conf.c                |  170 ++++++++++++++++++++++++++----------
 blacklist/lib/bl.c                  |   13 --
 blacklist/lib/blacklist.c           |    2 
 blacklist/libexec/blacklistd-helper |   14 --
 contrib/blacklist/port/config.h     |only
 9 files changed, 154 insertions(+), 91 deletions(-)
```

**Comment by emaste** [comment]
It looks like there are three changes from NetBSD that do not exist in our tree yet:

https://github.com/NetBSD/src/commit/518a28b2e752ec6a826235827b5108c99cd37c9c
https://github.com/NetBSD/src/commit/410356029f448a3a18e0436616237a67acb1d13a
https://github.com/NetBSD/src/commit/c3c0c82d94353af174963403d914d8b8b16ba28d

**Comment by emaste** [comment]
Once those are done I think we pick up at https://github.com/zoulasc/blocklist/commit/ea9c86bdbadced863ab73e40a5162cb6349cfc57

**Comment by jlduran** [comment]
Yes, currently working on them:

https://github.com/jlduran/freebsd-src/commit/02f1c1de12e9e3a0a9f23db05171582356d8c07f
https://github.com/jlduran/freebsd-src/commit/fe665ad65b1633ee97b071f5c68d517dc2068956
https://github.com/jlduran/freebsd-src/commit/09cc6f94f10629092501155fb030a72024fa30e7
https://github.com/jlduran/freebsd-src/commit/7f2af3d8a0646537d2572aef7c36eea766062c73

You'll receive a PR shortly.

Also upstreaming some of our changes:

https://github.com/zoulasc/blocklist/pull/5
https://github.com/zoulasc/blocklist/pull/6

Thank you!

**Comment by bsdimp** [comment]
Can we close this?

**Comment by jlduran** [comment]
> Can we close this?

Cleaning up the the (GitHub) house? — Nice!
Yes, I think I'll close both PRs related to blocklistd. I believe there are a couple more changes that were accepted upstream.
But the overall goal of facilitating/reducing the diffs with upstream has been achieved.
Thank you! @emaste

**Comment by bsdimp** [comment]
Thanks @jlduran !

**Comment by emaste** [comment]
@jlduran I think I have one more change from you to bring in (staged in my local repo), to get us to just before the upstream rename.

**Comment by jlduran** [comment]
My current diff: https://github.com/jlduran/freebsd-src/compare/main...jlduran:freebsd-src:upgrade-blocklistd

**Pull request closed without merging**
