### PR TITLE
 usr.sbin/bluetooth/hccontrol/bluetooth.device.conf: fix comment

### PR DESCRIPTION
**Pull request by lherschi**

### CODE REVIEW

**Review by gmshake — APPROVED** [review]
LGTM.

**Comment by gmshake** [comment]
And now it is also consistent with the man page.

**Comment by bsdimp** [comment]
I'll go ahead and land this, since it's correct.
To make this submission better in the future, please put the following in the git commmit message (I was able to cut and paste from here, but it will save me time if this is in the initial submission):

1.  Add the title to the pull-request as the first line in the commit message followed by a blank line
2. Add a longer comment about fixing the default, and merge in the reviewer feedback that it makes the comments match the man page now.
3. Add the Event: line for this course (if that's what it's from).

**Comment by lherschi** [comment]
I have nothing to do with the event in the commit message.

**Pull request closed without merging**
