### PR TITLE
file_test: Fix file test

### PR DESCRIPTION
**Pull request by jlduran**
Trimming of the line feed is no longer necessary after https://github.com/file/file/commit/d993c6b0db20711b2c4cb9d2bee8c7f2e59b0a43.
Currently the tests:
  - bcachefs2
  - gpkg-1-zst
  - multiple

are failing, but a fix will be committed upstream.

### CODE REVIEW

**Comment by jlduran** [comment]
cc/ @delphij @emaste

**Comment by jlduran** [comment]
For completeness, here is the GitHub Pull Request: https://github.com/file/file/pull/134
The fix for `multiple` may require a change in our test script, similar to what was done upstream in: https://github.com/file/file/commit/b74150490be904801378b2712fe0d532e1700124 (`.flags` file, etc.)

**Comment by delphij** [comment]
Thanks!

**Comment by jlduran** [comment]
I would kindly like to request an MFC to stable/14 of the following commits:
- https://github.com/freebsd/freebsd-src/commit/0d3a87569f14b0e48826bbaab5e05f35669bcebf
- https://github.com/freebsd/freebsd-src/commit/8f75390c66bdcde95e1b383aecaa27b4adf88279

Reported by: Jenkins
https://ci.freebsd.org/view/Test/job/FreeBSD-stable-14-amd64-test/lastBuild/testReport/junit/usr.bin.file/file_test/contrib_file_tests/

**Comment by emaste** [comment]
> I would kindly like to request an MFC to stable/14 of the following commits:

Done, 660be17a01ff

**Comment by jlduran** [comment]
Thank you. Initially I missed (I edited the comment):
https://github.com/freebsd/freebsd-src/commit/3347078000c078f2e67214ef1ba2e0bffe1aea4f
(which has already been committed upstream) without that newline, the test will fail.

**Comment by emaste** [comment]
687bf7433c3d

**Pull request closed without merging**
