### PR TITLE
snd_hda(4) pin fixes realtek ALC293

### PR DESCRIPTION
**Pull request by kstaring**
As with previous patches, earlier branches are also contained in this one. Also, pin patches were ported provided the Linux sources were clear-- entries that looked suspiciously like human error (e.g. double entries, unknown pci vendor ids) weren't ported.

### CODE REVIEW

**Comment by kstaring** [comment]
PS: I can also combine all of these pull requests into one big one now, or when Realtek's ready. Continuing by generating a pull request per ALC branch is also fine by me-- whatever's best for a committer.

**Comment by seanbruno** [comment]
Nah, this is kind of awesome in this manner.  I'm testing each one right now for compilation only.

It'll make it a lot easier to bisect in SVN if you continue the process you started here (one patch per device ID).

**Comment by ykla** [comment]
Do you have ALC233?

**Comment by bsdimp** [comment]
I've taken all these pull requests, squashed them and forward ported them to -current. https://reviews.freebsd.org/D30619 is the review. As such, I'm going to close all these here.

**Pull request closed without merging**
