### PR TITLE
mqueuefs: Do not call taskqueue_enqueue

### PR DESCRIPTION
**Pull request by ricardobranco777**
Fixes crash https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278936

### CODE REVIEW

**Comment by bsdimp** [comment]
I think we need an explanation about why this fixes that bug in the commit message.

**Comment by ricardobranco777** [comment]
> I think we need an explanation about why this fixes that bug in the commit message.

I wish I knew that lol.

**Comment by bsdimp** [comment]
> > I think we need an explanation about why this fixes that bug in the commit message.
> 
> I wish I knew that lol.

what made you try it then?

**Comment by ricardobranco777** [comment]
> > > I think we need an explanation about why this fixes that bug in the commit message.
> > 
> > 
> > I wish I knew that lol.
> 
> what made you try it then?

The stack trace in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278936 contains this call.

**Comment by bsdimp** [comment]
So, the task of the taskqueue was do_recyle:
```
/*                                                                                                                                                                                                                                                                              
 * task routine                                                                                                                                                                                                                                                                 
 */
static void
do_recycle(void *context, int pending __unused)
{
        struct vnode *vp = (struct vnode *)context;

        vn_lock(vp, LK_EXCLUSIVE | LK_RETRY);
        vrecycle(vp);
        VOP_UNLOCK(vp);
        vdrop(vp);
}
```
so we're "leaking" vnodes I think by not calling it since we never drop the hold we take out in the loop (at the very least) and we never recycle it.

I see there's a sx lock protecting things, but I don't see what protects a race with mqfs_reclaim. Once it gets the lock, it assumes that it can just remove the vd from the list without checking to see if the mqfs_node is still valid or not... So we call do_unlink, queue all this work up, drop the lock, then mqfs_reclaim runs, frees the node and then the task thread runs and BOOM since it's run on a now-free'd mqfs_vdata? And by removing the taskqueue queueing we avoid the panic?

**Comment by kostikbel** [comment]
https://reviews.freebsd.org/D45305 is an attempt to provide the proper fix.

**Pull request closed without merging**
