### PR TITLE
libbe(3), bectl(8): corrections, changes

### PR DESCRIPTION
**Pull request by grahamperrin**
Add AUTHORS to libbe(3), and make its HISTORY section consistent with
bectl(8).

beadm(1) no longer exists.

Improve the HISTORY and AUTHORS sections of bectl(8), including
consistency with the manual pages for beadm(8) and libbe(3).

For comparison, if required (online): 

* `freebsd-ports` beadm(8) <https://man.freebsd.org/cgi/man.cgi?query=beadm&sektion=8&manpath=freebsd-ports>
* `freebsd-release` libbe(3) <https://man.freebsd.org/cgi/man.cgi?query=libbe&sektion=3&manpath=freebsd-release>
* `freebsd-release` bectl(8) <https://man.freebsd.org/cgi/man.cgi?query=bectl&sektion=8&manpath=freebsd-release>

### CODE REVIEW

**Comment by grahamperrin** [comment]
Discussed with @kevans91.

This PR finds no conflict with https://github.com/freebsd/freebsd-src/commit/9b03a5de73d41f98b9b3c8e250a58f62f3e48d61 for bectl(8). 

Rendered HISTORY and AUTHORS of libbe(3) and bectl(8) (excluding 9b03a5de73d41f98b9b3c8e250a58f62f3e48d61), respectively: 

----

```text
HISTORY
     libbe and libbe(3) were written by Kyle Kneitinger (kneitinger)
     <kyle@kneit.in> as a 2017 Google Summer of Code project, with Allan Jude
     (allanjude) <allanjude@freebsd.org> as mentor.

AUTHORS
     Kyle Kneitinger, mentored as above.

     Post-GSoC changes were written by Kyle Evans (kevans)
     <kevans@freebsd.org>.
```

----

```text
HISTORY
     bectl and libbe(3) were written by Kyle Kneitinger (kneitinger)
     <kyle@kneit.in> as a 2017 Google Summer of Code project, with Allan Jude
     (allanjude) <allanjude@freebsd.org> as mentor.

     bectl and this manual page were derived from beadm(8).

AUTHORS
     Slawomir Wojciech Wojtczak (vermaden) <vermaden@interia.pl> is the
     creator and maintainer of beadm(8).
     Bryan Drewery (bdrewery) <bryan@shatow.net> contributed child dataset
     fixes, and wrote the beadm(8) manual page.

     Most later changes to bectl, and to this page, were written by
     Kyle Evans (kevans) <kevans@freebsd.org>.
```

**Review by igalic — APPROVED** [review]
looks good now! 👍

**Comment by bsdimp** [comment]
763f5da97dfd11e80c60cf6a7df6ae3a221f2519

**Comment by grahamperrin** [comment]
Merge to STABLE? 

Sorry, I forgot to suggest an MFC. 

> `freebsd-release` bectl(8) [man.freebsd.org/cgi/man.cgi?query=bectl&sektion=8&manpath=freebsd-release](https://man.freebsd.org/cgi/man.cgi?query=bectl&sektion=8&manpath=freebsd-release)

- currently for 14.1-RELEASE, still contains the four references to nonexistent beadm(1), and so on. 

### Side note

I don't understand why <https://man.freebsd.org/cgi/man.cgi?query=beadm&sektion=1&manpath=FreeBSD+Ports+14.1> is found in section 1. The page's section was changed to 8 in December 2020 – <https://github.com/vermaden/beadm/commits/master/beadm.8>.

**Pull request closed without merging**
