### PR TITLE
Address self reference links: open.2 mdmfs.8 cfumass.4 bhnd_erom.9 device_add_child.9

### PR DESCRIPTION
**Pull request by chrisdavidson**
open.2 - Changed openat .Xr reference to .Nm
mdmfs.8 - Updates to .Xr references
cfumass.4 - Updates to .Xr references
bhnd_erom.9 - Updates to .Xr references
device_add_child.9 - Updates to .Xr references

### CODE REVIEW

**Review by concussious — APPROVED** [review]

**Comment by concussious** [comment]
I'm not sure if editing the title just makes a bunch of noise and is actually unhelpful, but if it's good, you could probably improve it by clarifying the pr title to mention the subsystem e.g. "manpages: fix 5 self-references".

**Comment by chrisdavidson** [comment]
thank you @concussious for the review and the tidbits. 

The amount of detail to put in a git commit has been a learning, i went with being more extensive as this is pretty new. Your suggestion on maybe less is more is a good thing and will try that with the next one (if that makes sense to do).

**Comment by chrisdavidson** [comment]
denoting this commit message is aligned to the conventions for the project.

**Comment by chrisdavidson** [comment]
hi @mhorne if it would not be too much trouble, could you take a look at this pull request? 

I went through and aligned things, got it down to 1 commit and did the commit log magic on it.

Thank you in advance.

**Review by mhorne — APPROVED** [review]
I ended up splitting it into separate commits for each page. This is slightly preferred, because it allows individual pieces to be reverted, if necessary.

You can now close the PR!

**Comment by chrisdavidson** [comment]
thank you, i will make note of that future updates.

**Pull request closed without merging**
