### PR TITLE
Prune old support

### PR DESCRIPTION
**Pull request by bsdimp**
This is mostly a test of our current CI stuff...

### CODE REVIEW

**Comment by bsdimp** [comment]
Pushed as a420a672bc53 since this built

**Comment by arichardson** [comment]
I'm pretty sure these are needed for Linux+macos builds since the host tools don't support all calls used in the build. We should really add a full cross-build buildworld CI.

**Comment by bsdimp** [comment]
> I'm pretty sure these are needed for Linux+macos builds since the host
> tools don't support all calls used in the build. We should really add a
> full cross-build buildworld CI
>
 What's a good test then? Full buildworld on Linux? I thought that was part
of the build on github already...

Warner

**Comment by arichardson** [comment]
I only enabled buildkernel since buildworld took quite a long time on the GitHub hosted builders. I haven't tried recently but it might make sense to add buildworld (-DWITHOUT_TOOLCHAIN to avoid building LLVM) to the GitHub action to see how long it takes.

**Comment by bsdimp** [comment]
OK. I was mistaken about what was being tested and showing green. I'll toss
a tree onto one of my ubuntu VMs to build before I commit again

**Comment by emaste** [comment]
We could add a full cross-build test in Cirrus-CI if we want, but would want to make it on demand (as with the arm64 smoke test) to avoid consuming too much of Cirrus-CI's free resources.

**Pull request closed without merging**
