### PR TITLE
sbin/dump /dump.h typo

### PR DESCRIPTION
**Pull request by yue0211**
Name :  Yu-Yueh Chang
Email : asx5566123@gmail.com
Line 100 :   mapping rouintes   ->    mapping routines 
Event : from the Advanced UNIX Programming Course (Fall’23) at NTHU.

### CODE REVIEW

**Comment by lwhsu** [comment]
The name and emails are different in the comment are different than what in the `From:` (`Author:` in git) in https://github.com/freebsd/freebsd-src/pull/968.patch . What's your preference?

**Comment by yue0211** [comment]
I thought the class requirement was that I need to leave my real name.

my account name called yue0211 and the Author name in git are the same.

email name in comment  and in git are the same called asx5566123@gmail.com

**Comment by lwhsu** [comment]
The please still include `Event: Advanced UNIX Programming Course (Fall’23) at NTHU` in the last line of the commit message, with a single blank line above it.

**Review by lwhsu — APPROVED** [review]

**Comment by lwhsu** [comment]
Merged as 26e69f9f98bf976b0f898f1fcb9ca572a0f22c54

**Pull request closed without merging**
