### PR TITLE
newfs: prefer unsigned index over signed

### PR DESCRIPTION
**Pull request by AtariDreams**
We can just use a for loop starting at 0 instead of a while loop starting at -1.

### CODE REVIEW

**Review by igalic — APPROVED** [review]
👍

**Comment by ngie-eign** [comment]
Please change the email address to a non-users.noreply.github.com based address.
If you use `git config user.email`, etc, then run `git commit --reset-author --amend`, it will update the authorship appropriately.

**Comment by AtariDreams** [comment]
> Please change the email address to a non-users.noreply.github.com based address. If you use `git config user.email`, etc, then run `git commit --reset-author --amend`, it will update the authorship appropriately.

Done!

**Comment by bsdimp** [comment]
I think it's good. I've asked kirk to take a look.

**Comment by bsdimp** [comment]
Pushed as 430168942f2b

**Comment by bsdimp** [comment]
> +1

Doh! I missed this review when I pushed. I'm sorry.

**Pull request closed without merging**
