### PR TITLE
Fix typo (triple T)

### PR DESCRIPTION
**Pull request by jlduran**

### CODE REVIEW

**Review by bsdimp — APPROVED** [review]

**Review by igalic — CHANGES_REQUESTED** [review]
can you please amend your commit messages with a reference to this pull request

**Comment by bsdimp** [comment]
> can you please amend your commit messages with a reference to this pull request

There's no need. My script adds that automatically

**Comment by jlduran** [comment]
> > can you please amend your commit messages with a reference to this pull request
> 
> There's no need. My script adds that automatically

Sorry about that. Reverted!

**Comment by bsdimp** [comment]
merged.

**Pull request closed without merging**
