### PR TITLE
Disable capsicum on md5 et al

### PR DESCRIPTION
**Pull request by ricardobranco777**
Quick fix for https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276043

### CODE REVIEW

**Comment by markjdb** [comment]
I don't think this is the right move. The problem is specific to the cpuinfo file. md5, wc, etc., are not broken in general, it's just that cpuinfo behaves different when read from a capsicum sandbox. Setting CTFLAG_CAPRD on the hw.model sysctl (like we already do for the hw.machine sysctl) should fix the problem.

**Comment by ricardobranco777** [comment]
> I don't think this is the right move. The problem is specific to the cpuinfo file. md5, wc, etc., are not broken in general, it's just that cpuinfo behaves different when read from a capsicum sandbox. Setting CTFLAG_CAPRD on the hw.model sysctl (like we already do for the hw.machine sysctl) should fix the problem.

Where is that done?  Couldn't find anything with CTFLAG_CAPRD.

**Comment by markjdb** [comment]
> > I don't think this is the right move. The problem is specific to the cpuinfo file. md5, wc, etc., are not broken in general, it's just that cpuinfo behaves different when read from a capsicum sandbox. Setting CTFLAG_CAPRD on the hw.model sysctl (like we already do for the hw.machine sysctl) should fix the problem.
> 
> Where is that done? Couldn't find anything with CTFLAG_CAPRD.

I meant to write CTLFLAG_CAPRD. A proposed patch is here: https://reviews.freebsd.org/D43281

**Comment by ricardobranco777** [comment]
> > > I don't think this is the right move. The problem is specific to the cpuinfo file. md5, wc, etc., are not broken in general, it's just that cpuinfo behaves different when read from a capsicum sandbox. Setting CTFLAG_CAPRD on the hw.model sysctl (like we already do for the hw.machine sysctl) should fix the problem.
> > 
> > 
> > Where is that done? Couldn't find anything with CTFLAG_CAPRD.
> 
> I meant to write CTLFLAG_CAPRD. A proposed patch is here: https://reviews.freebsd.org/D43281

Thanks.

But the md5 code needs a fix anyway for the `XXX` block.  Why only the last argument?

**Comment by markjdb** [comment]
> > > > I don't think this is the right move. The problem is specific to the cpuinfo file. md5, wc, etc., are not broken in general, it's just that cpuinfo behaves different when read from a capsicum sandbox. Setting CTFLAG_CAPRD on the hw.model sysctl (like we already do for the hw.machine sysctl) should fix the problem.
> > > 
> > > 
> > > Where is that done? Couldn't find anything with CTFLAG_CAPRD.
> > 
> > 
> > I meant to write CTLFLAG_CAPRD. A proposed patch is here: https://reviews.freebsd.org/D43281
> 
> Thanks.
> 
> But the md5 code needs a fix anyway in the `XXX` block. Why only the last argument?

It's because md5 was sandboxed before cap_fileargs(3) was introduced. That library lets one access an arbitrary list of files from within a capability mode sandbox. md5 should be converted to use cap_fileargs(3). wc(1) already does: see the uses of fileargs_*. If you'd like to work on this, please cc me on the PR and I'll help get it landed.

**Pull request closed without merging**
