### PR TITLE
rename KB_DELAY to KBD_DELAY, enable use via KERNCONF, update docs

### PR DESCRIPTION
**Pull request by paepckehh**
new approach for #647  

Allow the customization of KBD_DELAY as  KERNCONF option, consistently rename existing KB_DELAY to KBD_DELAY to keep kernel option prefix consistent, add docs.

Existing KERNCONF options for the KBD_ prefix are:
```
[...]
# kbd options
KBD_DISABLE_KEYMAP_LOAD	opt_kbd.h
KBD_INSTALL_CDEV	opt_kbd.h
KBD_MAXRETRY		opt_kbd.h
KBD_MAXWAIT		opt_kbd.h
KBD_RESETDELAY		opt_kbd.h
KBDIO_DEBUG		opt_kbd.h
[...]
```

This unlocks:
* allow to customize this parameter within user land less embedded and security appliances
* allow to specify custom parameter-sets that are not supported via kbdcontrol fixed ranges/sets

No change in default behavior .

CI tests: [D38603](https://reviews.freebsd.org/D38603)

### CODE REVIEW

**Comment by paepckehh** [comment]
updates done for atkbc.4 and UPDATING as requested,
added an (optional) NOTES entry as proposal

**Comment by bsdimp** [comment]
I think we're super close now. I'll download it tomorrow (later in your day :) and see if there's anything last minute that needs changing, or if I need you to do anything else.

**Comment by paepckehh** [comment]
> I think we're super close now. I'll download it tomorrow (later in your day :) and see if there's anything last minute that needs changing, or if I need you to do anything else.

Thank you! Yes, GitHub really needs a local daylight indicator, flagging overlapping hours.
Hope we are still fast enough to MFC for 13.2?

**Comment by igalic** [comment]
it exists, but is only shown on the desktop view.

in addition, i live in Ireland (Republic) but as far as timezone selection goes, i get London, Edinburgh, Lisabon and Monrovia.

i think someone at GitHub needs to learn about the strained political relationships these islands have

**Comment by bsdimp** [comment]
Landing... folded a few commits together and had to fix some trailing white space.

**Comment by bsdimp** [comment]
Also, next time, when updating, please update with a rebase rather than a merge...

**Comment by paepckehh** [comment]
> Also, next time, when updating, please update with a rebase rather than a merge.

Yes, sorry for that. Its always tempting to use the github web interface for small fixes 
like this. But at the end its always a mess. For new requests I will migrate back to a native
git tool set & workflow.

Thank you for your great support!

**Pull request closed without merging**
