### PR TITLE
p9fs.5: rename to p9fs.4

### PR DESCRIPTION
**Pull request by llfw**
This is a filesystem (driver), not a file format, so it should be in section 4.

### CODE REVIEW

**Comment by Rin0913** [comment]
As my personal opinion, I think it seems to be reasonable to categorize in man 5 because P9 is nothing but a protocol instead of a device driver in the very begin. However, rename to p9f.4 is acceptable now while a manual should still exist describing the protocol itself.

**Comment by llfw** [comment]
> In my opinion, it seems reasonable to categorize it under man 5 because P9 was originally a protocol instead of a device driver.

are protocols normally in section 5 ('File Formats')?  ip(4) is in section 4, for example.

**Comment by concussious** [comment]
Section 5 is the File Formats Manual. All filesystem driver manuals have been moved to section 4 with the other drivers for FreeBSD 15.

**Comment by Rin0913** [comment]
Sorry for that, I got confused. Section 5 is indeed for file format only.
I was thinking that the protocol format was included inside.
I apologized for my mistake.

**Comment by bsdimp** [comment]
Filesystems have been moved to section 4 recently. They used to be in section 5.
So I'm not sure why this isn't correct.
p9fs landed in the middle of that transition.

**Comment by markjdb** [comment]
> can we get this merged as it's obviously correct?

It's incomplete. Obsoletefiles.inc needs an entry `OLD_FILES+=usr/share/man/man5/p9fs.5.gz`.

**Comment by llfw** [comment]
fixed

**Review by concussious — APPROVED** [review]

**Pull request closed without merging**
