### PR TITLE
daemon: move variables into struct daemon_state

### PR DESCRIPTION
**Pull request by ngortheone**
The fact that most of the daemon's state is stored on the stack of the main() makes it hard to split the logic smaller chunks. Which in turn leads to huge main func that does a a lot of things. `struct log_params` existed because some variables need to be passed into other functions together.

This change renames `struct log_params` into `daemon_state` and moves the rest of the variables into it. This is a necessary preparation step for further refactoring.

### CODE REVIEW

**Comment by ngortheone** [comment]
@bsdimp this is a smaller portion of https://github.com/freebsd/freebsd-src/pull/684

**Comment by ngortheone** [comment]
cc @kevans91

**Comment by bsdimp** [comment]
This looks OK. I understand these bits fairly well...
What does 'make tests' tell you? Do they all still pass?

**Comment by ngortheone** [comment]
@bsdimp yes, I ran `kyua tests` in the tests directory after installing the binary that was built, all is good

**Comment by ngortheone** [comment]
```
> make
rm -f .depend
echo daemon.full: /usr/lib/libc.a /usr/lib/libutil.a >> .depend
cc  -O2 -pipe -fno-common -march=znver3  -fPIE -mretpoline -g -gz=zlib -MD  -MF.depend.daemon.o -MTdaemon.o -std=gnu99 -Wno-format-zero-length -fstack-protector-strong -Wsystem-headers -Werror -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wstrict-prototypes -Wchar-subscripts -Wnested-externs -Wold-style-definition -Wno-pointer-sign -Wdate-time -Wmissing-variable-declarations -Wthread-safety -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-error=unused-but-set-variable -Wno-error=array-parameter -Wno-error=deprecated-non-prototype -Wno-error=unused-but-set-parameter  -Qunused-arguments    -c daemon.c -o daemon.o
cc -O2 -pipe -fno-common -march=znver3 -fPIE -mretpoline -g -gz=zlib -std=gnu99 -Wno-format-zero-length -fstack-protector-strong -Wsystem-headers -Werror -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wstrict-prototypes -Wchar-subscripts -Wnested-externs -Wold-style-definition -Wno-pointer-sign -Wdate-time -Wmissing-variable-declarations -Wthread-safety -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-error=unused-but-set-variable -Wno-error=array-parameter -Wno-error=deprecated-non-prototype -Wno-error=unused-but-set-parameter -Qunused-arguments  -Wl,-znow -Wl,-zrelro -pie -Wl,-zretpolineplt   -o daemon.full daemon.o  -L/opt/ngor/src/git.freebsd.org/src/lib/libutil -lutil
objcopy --only-keep-debug daemon.full daemon.debug
objcopy --strip-debug --add-gnu-debuglink=daemon.debug  daemon.full daemon
gzip -cn daemon.8 > daemon.8.gz
===> tests (all)
echo '#! /usr/libexec/atf-sh' > daemon_test.tmp
cat daemon_test.sh >>daemon_test.tmp
chmod +x daemon_test.tmp
mv daemon_test.tmp daemon_test

> su -
Password:
root@zen:~ # cp -f /home/ngor/src/git.freebsd.org/src/usr.sbin/daemon/daemon /usr/sbin/daemon
root@zen:~ # chmod -w /usr/sbin/daemon
root@zen:~ # ^D

> cd tests/
[20:27:10] ngor@zen /home/ngor/src/git.freebsd.org/src/usr.sbin/daemon/tests
> kyua test
daemon_test:both_pidfile  ->  passed  [0.019s]
daemon_test:chdir  ->  passed  [0.013s]
daemon_test:child_pidfile  ->  passed  [0.013s]
daemon_test:child_pidfile_lock  ->  passed  [0.012s]
daemon_test:newsyslog  ->  passed  [0.438s]
daemon_test:output_file  ->  passed  [0.010s]
daemon_test:restart_child  ->  passed  [1.079s]
daemon_test:supervisor_pidfile  ->  passed  [0.014s]
daemon_test:supervisor_pidfile_lock  ->  passed  [0.012s]
daemon_test:title  ->  passed  [0.013s]
daemon_test:user  ->  skipped: Requires root privileges  [0.000s]

Results file id is opt_ngor_src_git.freebsd.org_src_usr.sbin_daemon_tests.20230312-042713-129675
Results saved to /home/ngor/.kyua/store/results.opt_ngor_src_git.freebsd.org_src_usr.sbin_daemon_tests.20230312-042713-129675.db

11/11 passed (0 failed)
```

**Comment by bsdimp** [comment]
Merged...

**Pull request closed without merging**
