### PR TITLE
libnvmf: avoid resource leak

### PR DESCRIPTION
**Pull request by khorben**
In nvmf_host_fetch_discovery_log_page(), the log variable may have been allocated on the heap during a first loop cycle, and should be free()'d again before exiting upon errors.

Reported by:	Coverity
CID:		1545034
Sponsored by:	The FreeBSD Foundation

### CODE REVIEW

**Comment by khorben** [comment]
Cc @bsdjhb

**Review by bsdimp — APPROVED** [review]
Looks fine..  borderline worth it because this usually is adjacent to an exitvpath, but it is in a library.

**Comment by bsdimp** [comment]
Tagged with 'ready' but I'll give it until tomorrow for @bsdjhb to take. peek

**Comment by bsdjhb** [comment]
The other error cases in the loop after the realloc all call free, so this is more consistent.

**Review by bsdjhb — APPROVED** [review]

**Comment by bsdjhb** [comment]
Would maybe s/first loop cycle/previous loop iteration/ in the log message.  "again" might also be confusing as you aren't calling free multiple times, so I would perhaps omit it from the log message.

**Comment by khorben** [comment]
> Would maybe s/first loop cycle/previous loop iteration/ in the log message. "again" might also be confusing as you aren't calling free multiple times, so I would perhaps omit it from the log message.

The `log` variable is always allocated in the first loop cycle initially (if there is more than one).
I have removed "again" from the log message.
Thanks!

**Pull request merged**
