### PR TITLE
Fix czech date and time formats

### PR DESCRIPTION
**Pull request by MichaelGrafnetter**
Changed the cs_CZ date format from 2015/05/12 to 05.12.2015.
Updated the cs_CZ translation of am/pm.

### CODE REVIEW

**Comment by mmoll** [comment]
I'm not a Czech native speaker, but should odp and dop have a dot at the end? The various sources differ on that one...

**Comment by MichaelGrafnetter** [comment]
You are right, abbreviations must have a dot at the end in Czech. But I am afraid that extending the am/pm strings  by another character might break outputs of some programs that have the length of the time string hard-coded in them. This is the reason I did not add the dots, although I hesitated for a moment there.
On the other hand, 12-hour time format is rarely used by the Czech.

**Comment by mmoll** [comment]
Sounds good to me. However the thing is, at the moment FreeBSD does not merge pull requests here, as SVN is used. Please open PR over at https://bugs.freebsd.org/bugzilla/ and attach your diff.

**Comment by mmoll** [comment]
@MichaelGrafnetter Anything I can do to help? If you don't want to hack it into Bugzilla, I can also open a PR for you with the diff.
BTW, thanks to you raising this, https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200273 got opened. :)

**Comment by MichaelGrafnetter** [comment]
@mmoll Thx, I think I can do that myself. I was just busy with other projects, so I have not done it yet.

**Comment by mmoll** [comment]
díky moc!

**Comment by bsdimp** [comment]
I think that this can be closed. Has this been integrated? I can't read czech well enough to know....

**Comment by mmoll** [comment]
@bsdimp there's on open PR about this for @MichaelGrafnetter and another one for Slovak from me, but nobody did care.

**Comment by emaste** [comment]
PR links:
Slovak: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200273
Czech: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200591

**Comment by bsdimp** [comment]
If the PRs are up to date, then we should let this play out there? Any objection to my going ahead and closing out this pull request?

**Comment by emaste** [comment]
Should it be "%d. %m. %Y" (with extra spaces)? Or perhaps that makes sense for typeset documents but not fixed-with cases?

@bsdimp I think this change is ready to go in (pending my comment), and we might as well commit from the pull request while there's momentum behind going through them.

**Comment by bsdimp** [comment]
@emaste just as happy to commit and close as redirect and close if it's a good change.

**Comment by emaste** [comment]
@MichaelGrafnetter any comment on the space question above? "%d. %m. %Y"

**Comment by dgerzo** [comment]
@emaste as native Slovak, I'd go without spaces.

**Comment by ondraknezour** [comment]
@edmaste As a native Czech, spaces are mandatory.

**Comment by bsdimp** [comment]
91d68affb0255 seems to have already landed this, or a similar fix.

**Pull request closed without merging**
