### PR TITLE
nanobsd: Set a GPT label for EFI and cfg partitions

### PR DESCRIPTION
**Pull request by jlduran**
This change is dependent on https://github.com/freebsd/poudriere/pull/1143, just to keep things similar (or it should be the other way around).

### CODE REVIEW

**Comment by jlduran** [comment]
Small rant on the topic: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278480 .

**Review by bsdimp — APPROVED** [review]
I love this... Maybe we could change bsdinstall to use efiboot, efiboot1, etc.
And I'd love to see a change to vmimage too. It's new enough we don't have a huge legacy to be compatible with.

**Comment by bsdimp** [comment]
On second thought, maybe we should standardize on `efiboot0`

**Comment by bsdimp** [comment]
landed. Thanks for the submission.

**Pull request closed without merging**
