### PR TITLE
psm(4): synaptics improvements

### PR DESCRIPTION
**Pull request by benlemasurier**
This fixes a few issues found within the psm(4) driver, specifically related to Synaptics touchpad usability. 

- Fix virtual scroll pointer movement issues
- Respect `hw.psm.tap_enabled=0`
- Ignore touchpad gestures when palm is detected
- Small code clarity cleanup

It appears as if FreeBSD is trending away from `sysmouse`/`moused` towards `EVDEV`/`libudev-devd` however I think this still a useful patchset given it's still packaged by default. 

Apologies if GitHub in an inappropriate place for submissions, happy to go through another channel if needed. Looking through closed pull requests this appears to be okay for smaller submissions.

- Tested on a Dell XPS 9360 with a synaptics touchpad

### CODE REVIEW

**Comment by vangyzen** [comment]
I'd like to commit your changes, but I'm having trouble testing them.  What config changes have you made to enable full trackpad functionality?  I also have a Dell XPS 9360.  When I set the tunable to enable synaptics support, the trackpad is unusable, with or without your changes.  For example, some click events seem to be lost, or delayed until some subsequent event, such as motion.  Two-finger scroll does not work.

I'm running head as of a week ago, with similar vintage packages.  I built drm-next from ports.  Dbus and hald are running; moused is not.  I haven't made any explicit config changes related to the mouse or X.

**Comment by benlemasurier** [comment]
I'm running head with moused, and without hald or dbus, basically a fresh install + xorg. Mind posting your `/var/log/Xorg.0.log`?

**Comment by vangyzen** [comment]
Starting moused fixes it.  Thanks!  Funny...in almost 19 years of running FreeBSD, I've never needed moused.

I'll test your changes soon.

**Comment by wulf7** [comment]
1. "psm: do not process gestures when palm is present" - this change is not 100% correct. psmsmoother() should be called after psmgestures(). Otherwise "cursor movement" <-> "scroll" state transition will be done with 1 mouse packet lag. I think psmgestures() call should be left in place wrapped with another one psmpalmdetect() condition check.
2. "psm: fixes vscroll pointer movement bug"  - this change is too radical. It just drops clickpad's 'click and drag' gesture support instead of fixing it.
3 & 4. LGTM. I'll commit them after some testing.

**Comment by wulf7** [comment]
Committed as r346456-346458 (with some changes)

Thanks!

**Comment by bsdimp** [comment]
Already committed... closing.

**Pull request closed without merging**
