### PR TITLE
Use calloc and memset instead of malloc and bcopy

### PR DESCRIPTION
**Pull request by AtariDreams**

### CODE REVIEW

**Comment by hselasky** [comment]
Looks good. Do you have a committer for this?

**Comment by hselasky** [comment]
Please rebase your patch and update the commit message.

**Comment by AtariDreams** [comment]
No I do not have a committer for this, sadly.

**Comment by bsdimp** [comment]
The rest of geom tends to prefer bzero over memset. Since there's no clear win from one vs the other in the kernel, and to be consistent with the rest of geom, I'm going to close this pull request. All the other changes have landed.

**Pull request closed without merging**
