### PR TITLE
sbin/sysctl/sysctl.c typo

### PR DESCRIPTION
**Pull request by Howardkhh**
Name: Hao-Yu Hou
Email: howard.hou.fan@elsa.cs.nthu.edu.tw
Line214: combind -> combine
Event: This is from the Advanced UNIX Programming Course (Fall’23) at NTHU.

### CODE REVIEW

**Review by igalic — APPROVED** [review]
👍

note, you don't really need to include

> Name: Hao-Yu Hou
> Email: howard.hou.fan@elsa.cs.nthu.edu.tw

in your commit message, given that it's already in the commit metadata

**Comment by lwhsu** [comment]
Please remove the name and email in the commit message, as above said, they are included in the commit metadata. You can use `git commit --amend` to update the commit message, and `git push -f` to update your branch and this pull request.

**Review by gmshake — APPROVED** [review]
LGTM.

**Comment by lwhsu** [comment]
Merged as 2e8ad2b698498a1c380d0d6fc5792b2c56926801

**Pull request closed without merging**
