### PR TITLE
lib/libsecureboot: Fix some typos

### PR DESCRIPTION
**Pull request by ElyesH**
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>

### CODE REVIEW

**Comment by uqs** [comment]
Hi there, I see that you're enthusiastic about fixing typos, but please note that most of these changes are of very low priority to the project. No user will ever see them, so they don't improve FreeBSD the OS at all, and they also don't help much with developing FreeBSD.

It will be unlikely that a committer will pick this up, I'm afraid.

Changes to `contrib` code need to be submitted upstream in any case, we will not merge those changes in.

**Comment by lwhsu** [comment]
Fixing the typos are still helpful, but please submit them separately with white space changes (for example the removing trailing white spaces), and/or through the issue tracker: https://bugs.freebsd.org and review system: https://reviews.freebsd.org/ . That will increase the visibility and easier for developers to review and commit (merge).

Also, as above said, changes under `contrib` directory have to submit to the upstream first, that area is for imported codes.

**Comment by bsdimp** [comment]
Whitespace changes have traditionally caused friction, so I'm hesitant on them.
But the typos do look interesting. It's easier for me to cherry pick them from a pull request (which is just another branch in git) than the bugs or reviews. 
What would be most helpful to reduce the noise would be to have the ones that are purely comments separated out from the ones that affect variable names in code. The comments require only a little oversight, while the ones that touch code require more careful review.

**Comment by ElyesH** [comment]
I think, that I accidentally closed this pull request.
I don't know how to re-open it.
should I push a new pull request ?

**Comment by ElyesH** [comment]
Please see https://github.com/freebsd/freebsd-src/pull/460
Thx

**Pull request closed without merging**
