### PR TITLE
mac_veriexec : extend veriexec to control deletion (unlink) and move (rename_from and rename_to) on protected files

### PR DESCRIPTION
**Pull request by darklem**
This patch intend to elevate the level of protection provided by the veriexec module on files by including new syscall hooks. This patch is inspired by NetBSD veriexec.

Functions implemented :

- mac\_veriexec\_vnode\_check\_unlink: Unlink on a file has been requested and requires validation. This function prohibits the deleting a protected file (or deleting one of these hard links, if any).
- mac\_veriexec\_vnode\_check\_rename\_from: Rename the file has been requested and must be validated. This function controls the renaming of protected file
- mac\_veriexec\_vnode\_check\_rename\_to: File overwrite rename has been requested and must be validated. This function prevent overwriting of a file protected (overwriting by mv command).

The 3 fonctions together aim to control the 'removal' (via unlink) and the 'mv' on files protected by veriexec. The intention is to reach the functional level of NetBSD veriexec.

### CODE REVIEW

**Comment by darklem** [comment]
Anything I should change/adapt to make it useful for FreeBSD ?

**Comment by bsdimp** [comment]
On the surface, this looks good to my eye.

I don't think the normal veriexec folks are on github that often, so I've sent an email off to them to get their attention. I don't know their github handles, or I'd @ them here.

**Comment by sgerraty** [comment]
Blocking rename looks fine, but blocking unlink would break our package system.
Perhaps a sysctl to control that?

**Comment by bsdimp** [comment]
> Anything I should change/adapt to make it useful for FreeBSD ?

Have you seen @sgerraty's suggestions?

**Comment by darklem** [comment]
> On the surface, this looks good to my eye.
> 
> 
> 
> I don't think the normal veriexec folks are on github that often, so I've sent an email off to them to get their attention. I don't know their github handles, or I'd @ them here. I should have done this when it came in, please accept my apologies for missing it at the time.

Sorry for the delay ! I just read this answer. Thank you!

**Comment by darklem** [comment]
> Blocking rename looks fine, but blocking unlink would break our package system.
> 
> Perhaps a sysctl to control that?

Thank you Simon. I will make a change and propose it asap.

**Comment by bsdimp** [comment]
@sgerraty in your court: I think the changes look OK, but I'm no expert.

**Comment by sgerraty** [comment]
>@sgerraty in your court: I think the changes look OK, but I'm no expert.

My github fu is obviously lacking, I cannot find/see the new change.

**Comment by darklem** [comment]
I add a sysctl to toggle the unlink optionally. Tell me if you think I should adapt or change something.
Thank you for the review

**Comment by darklem** [comment]
@sgerraty, I add a sysctl to toggle the unlink optionally. Tell me if you think I should adapt or change something.
Thank you for the review

**Comment by sgerraty** [comment]
On Thu, 09 Mar 2023 06:23:26 -0800, Darklem writes:
>
>@sgerraty, I add a sysctl to toggle the unlink optionally. Tell me if you thin
>k I should adapt or change something.

Thanks for that.

What I suggest is use a tunable (TUNABLE_INT_FETCH) and
use one of {block,guard,protect}_unlink as a better name than just
unlink,
Then in mac_veriexec_init we can decide whether to set
mpo_vnode_check_unlink or not based on that tunable.
That way we can avoid the overhead of the calls if they are going to do
nothing.

The tunable can be visible via systcl but should be read-only.

--sjg

**Comment by darklem** [comment]
Hi @sgerraty, I made the modifications based on your last suggestion. I hope it will be fine. 
Thank you again for the review.

**Review by sgerraty — APPROVED** [review]
This looks promising.
Thanks very much!

**Comment by darklem** [comment]
Thank you @sgerraty  and @bsdimp for your time

**Comment by bsdimp** [comment]
Landed in the tree. Had to do a number of style cleanups, mostly brace placements and > 80 columns (for future reference). If we'd not let this linger, or had a better style checking script, I'd have done one more round to get them fixed.

**Comment by darklem** [comment]
@bsdimp, thank you ! Would it be possible please to link the contribution to my github user ( @darklem ) ?  It seems to be linked to my login 'dl'. Thank you.

**Comment by bsdimp** [comment]
> @bsdimp, thank you ! Would it be possible please to link the contribution to my github user ( @darklem ) ? It seems to be linked to my login 'dl'. Thank you.

I'm not sure how to do that after the fact. All we have in our repo is the email address in the commit message submitted here. If there is a way we can do that w/o a forced push, I'm happy to do so.

**Comment by emaste** [comment]
We can add a .mailmap file mapping if you provide the appropriate entry.
```
Your Display Name <new_email@example.com> <dl@canigo.cat>
```

**Comment by darklem** [comment]
> We can add a .mailmap file mapping if you provide the appropriate entry.
> 
> ```
> 
> Your Display Name <new_email@example.com>
> 
> ```

Thanks for the advice
(Btw, could you please remove my email address from your comment? Just in case)

**Pull request closed without merging**
