### PR TITLE
sys: rename preprocessed assembly-language files to .S

### PR DESCRIPTION
**Pull request by ehem**
Even though assembly-language .s files aren't supposed to be run through
cpp, clearly all of these are being preprocessed (#include is a strong
indicator).  A few potentially non-preprocessed files remain named .s.

Differential Revision: https://reviews.freebsd.org/D35908

### CODE REVIEW

**Comment by ehem** [comment]
Simply rebased since the main branch got pushed.  Clearly all the checks passed though.

**Comment by emaste** [comment]
This pull request was for the .s to .S rename; other changes should be in other pull requests? Anyhow no harm in grabbing other commits from here as you review/approve.

**Comment by bsdimp** [comment]
Yea, they should be, but the overhead for the two I just landed in asking for them to be so was too large for me :)

**Comment by bsdimp** [comment]
I've committed the last of the original changes from this that are no-brainers to commit.
What's the status of the rest of them? They appear to be in review, under active development, etc. That generally suggests that we close the PR unless there's a reason to keep it open...

**Comment by bsdimp** [comment]
Closing this pull request... It's expanded somewhat beyond it's original remit... All changes that don't need discussion and/or additional work have landed.

**Pull request closed without merging**
