### PR TITLE
Nuageinit fixes

### PR DESCRIPTION
**Pull request by jlduran**
Nuageinit fixes.

### CODE REVIEW

**Comment by jlduran** [comment]
Hi @bapt I have been working on nuageinit, and I expect to have a buffet of commits ready (soon-ish). Like a buffet chef, I would not mind you not liking all of the commits. But, is it something you are interested in reviewing?

In the meantime, these two commits are somewhat important:
- One fixes CI
- Two allows nuageinit to set the home directory to something other than `/home/whatever`

Thank you!

**Review by bsdimp — APPROVED** [review]
My eye says these are all good. I'll give @bapt through the weekend to comment, then I'll land it.

**Comment by bsdimp** [comment]
I almost rage committed something to disable the ci issue... So I'm glad to see it's being properly fixed here.

**Comment by jlduran** [comment]
> I almost rage committed something to disable the ci issue... So I'm glad to see it's being properly fixed here.

I felt terry bad for breaking the hard-earned streak of greens in CI (test-main).

**Comment by bapt** [comment]
merged thanks!

**Pull request closed without merging**
