### PR TITLE
hda pin fixes for realtek ALC880

### PR DESCRIPTION
**Pull request by kstaring**
This patch adds a new structure to separate patch data from logic. Realtek patches already present in the if/elseif list were moved to the new structure. Most of the Linux Realtek ALC880 pin patches are ported as well. (Linux patch entries with unknown vendor ids or NULL model names were ignored in the porting process.)
Notably missing: non-pin patches such as GPIO and custom Linux patch functions.

### CODE REVIEW

**Comment by grimreaper** [comment]
Has this this been applied yet? It does not apply cleanly

```
∴git am 139.patch
Applying: Patch to enable correct sound output on jack plug on the Dell XPS 9560 laptop.
error: patch failed: sys/dev/sound/pci/hda/hdaa_patches.c:410
error: sys/dev/sound/pci/hda/hdaa_patches.c: patch does not apply
error: patch failed: sys/dev/sound/pci/hda/hdac.h:201
error: sys/dev/sound/pci/hda/hdac.h: patch does not apply
Patch failed at 0001 Patch to enable correct sound output on jack plug on the Dell XPS 9560 laptop.
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
hub am 139.patch 0.21s user 4.42s system 747% cpu 0.619 total; max RSS 25072Ki
 0.06s user 3.92s system 1277% cpu 0.311 total; max RSS 25496Ki
```

I'll be happy to re-review and apply if you rebase on the latest HEAD / master.

**Comment by opntr** [comment]
@grimreaper: try with git am -3

**Comment by grimreaper** [comment]
```
Applying: Patch to enable correct sound output on jack plug on the Dell XPS 9560 laptop.
Using index info to reconstruct a base tree...
M	sys/dev/sound/pci/hda/hdaa_patches.c
M	sys/dev/sound/pci/hda/hdac.h
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Add support for Dell Latitude E7240 audio jack output.
Applying: rename DELL_LATITUDE_E7240 to DELL_E7240_SUBVENDOR for consistency
Applying: - Added pin_patch structures to separate data from logic. - Integrated Realtek patches into new structure. - Ported Linux ALC880 pin patches.
.git/rebase-apply/patch:758: space before tab in indent.
        				{
.git/rebase-apply/patch:759: space before tab in indent.
                				.nid = 16,
.git/rebase-apply/patch:760: space before tab in indent.
                				.type = PIN_PATCH_STRING,
.git/rebase-apply/patch:761: space before tab in indent.
                				.patch.string = "seq=15 device=Headphones"
.git/rebase-apply/patch:762: space before tab in indent.
        				}, { }
warning: squelched 23 whitespace errors
warning: 28 lines add whitespace errors.
Using index info to reconstruct a base tree...
.git/rebase-apply/patch:758: space before tab in indent.
        				{
.git/rebase-apply/patch:759: space before tab in indent.
                				.nid = 16,
.git/rebase-apply/patch:760: space before tab in indent.
                				.type = PIN_PATCH_STRING,
.git/rebase-apply/patch:761: space before tab in indent.
                				.patch.string = "seq=15 device=Headphones"
.git/rebase-apply/patch:762: space before tab in indent.
        				}, { }
warning: squelched 23 whitespace errors
warning: 28 lines add whitespace errors.
Falling back to patching base and 3-way merge...
error: The following untracked working tree files would be overwritten by merge:
	sys/dev/sound/pci/hda/pin_patch.h
	sys/dev/sound/pci/hda/pin_patch_realtek.h
Please move or remove them before you merge.
Aborting
error: Failed to merge in the changes.
Patch failed at 0004 - Added pin_patch structures to separate data from logic. - Integrated Realtek patches into new structure. - Ported Linux ALC880 pin patches.
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
hub am -3 139.patch 3.35s user 10.39s system 6% cpu 3:20.66 total; max RSS 42292Ki
```

**Comment by grimreaper** [comment]
```
Applying: Patch to enable correct sound output on jack plug on the Dell XPS 9560 laptop.
Using index info to reconstruct a base tree...
M	sys/dev/sound/pci/hda/hdaa_patches.c
M	sys/dev/sound/pci/hda/hdac.h
Falling back to patching base and 3-way merge...
Auto-merging sys/dev/sound/pci/hda/hdac.h
CONFLICT (content): Merge conflict in sys/dev/sound/pci/hda/hdac.h
Auto-merging sys/dev/sound/pci/hda/hdaa_patches.c
CONFLICT (content): Merge conflict in sys/dev/sound/pci/hda/hdaa_patches.c
Recorded preimage for 'sys/dev/sound/pci/hda/hdaa_patches.c'
Recorded preimage for 'sys/dev/sound/pci/hda/hdac.h'
error: Failed to merge in the changes.
Patch failed at 0001 Patch to enable correct sound output on jack plug on the Dell XPS 9560 laptop.
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
hub am -3 ~/patches/139.patch 1.48s user 4.17s system 166% cpu 3.393 total; max RSS 63936Ki
 0.14s user 2.82s system 659% cpu 0.448 total; max RSS 21548Ki
```

**Comment by kstaring** [comment]
Hmm, will look at this soon. Does the hda_pin_fixes_realtek branch apply correctly?

**Comment by kstaring** [comment]
Excuse me, other duties are interfering at the moment, will get back at the pull requests next week!

**Comment by kstaring** [comment]
@grimreaper can you try again? Thanks!

**Comment by grimreaper** [comment]
My computer is back to normal. Now the branch conflicts again. Mind rebasing?

**Comment by kstaring** [comment]
Weird how git wouldn't be able to resolve this..? Is it better now?

**Comment by vangyzen** [comment]
Merging your branch into master gives a syntax error.  The change in 8bb6dc1 puts an "else if" after an "else".  If I rebase your branch onto master, the syntax is fine, but the change in 8bb6dc1 is completely lost.  That's unfortunate, because that's my laptop.  :)  Is that change still needed, or was it reformulated into a different change?

**Comment by kstaring** [comment]
The change in 8bb6dc1 was indeed reformulated, it's now present in the realtek_pin_patches struct in pin_patch_realtek.h (see the struct at line 266). It should still work-- the XPS 9650 is my laptop also ;)
Strange that I couldn't get the syntax error to manifest.. Anyway, rebasing seems to do the right thing, the 8bb6dc1 change is obsoleted.

**Comment by bsdimp** [comment]
I've taken all these pull requests, squashed them and forward ported them to -current. https://reviews.freebsd.org/D30619 is the review. As such, I'm going to close all these here.

**Comment by bsdimp** [comment]
I've taken all these pull requests, squashed them and forward ported them to -current. https://reviews.freebsd.org/D30619 is the review. As such, I'm going to close all these here.

**Pull request closed without merging**
