### PR TITLE
Fix typo of tcsh nls set 9 in greek

### PR DESCRIPTION
**Pull request by chrislongros**

### CODE REVIEW

**Comment by igalic** [comment]
given that this is in Contrib, it needs to go upstream (first):  https://www.tcsh.org/ -> https://bugs.astron.com/my_view_page.php

**Comment by chrislongros** [comment]
> given that this is in Contrib, it needs to go upstream (first): https://www.tcsh.org/ -> https://bugs.astron.com/my_view_page.php

Should I open a pull request here: https://github.com/tcsh-org/tcsh ?

**Comment by igalic** [comment]
unfortunately, they have pull requests disabled, and issues seem to be ignored, so i would try https://bugs.astron.com/my_view_page.php

**Comment by bsdimp** [comment]
So how does one submit patches upstream for this? If there is no effective upstream anymore, we make the changes locally...

**Comment by asomers** [comment]
I don't know what @igalic is looking at.  Pull requests are definitely not disabled on tcsh's github page.

**Comment by chrislongros** [comment]
> I don't know what @igalic is looking at. Pull requests are definitely not disabled on tcsh's github page.

I agree. I submitted my pull requests yesterday.

**Comment by igalic** [comment]
yeah, sorry about that.

someone in GitHub's design team thought it was a good idea to hide pull requests on mobile, and I keep forgetting that.

**Pull request closed without merging**
