### PR TITLE
ps3: add elfv2 support

### PR DESCRIPTION
**Pull request by aomsin2526**
ps3 are broken since we moved to clang/elfv2. (13.0)

This commit will fix it. And will allow kernel to boot

If you have any issue with petitboot loading the kernel, consider trying this instead: https://github.com/aomsin2526/ps3-petitboot-kexec-patched

### CODE REVIEW

**Comment by chmeeedalf** [comment]
Looks good!  I'm surprised anyone is still running FreeBSD on a PS3.

**Comment by bsdimp** [comment]
Already merged.

**Comment by chmeeedalf** [comment]
Oops, sorry.  Thanks for closing it.

**Comment by bsdimp** [comment]
@aomsin2526 So how are you booting this kernel? With or without loader.kboot? Or is it entirely with petiboot?

**Comment by aomsin2526** [comment]
> @aomsin2526 So how are you booting this kernel? With or without loader.kboot? Or is it entirely with petiboot?

Just petitboot. /boot/kernel/kernel itself is fully compatible with petitboot just like linux.

**Pull request closed without merging**
