### PR TITLE
nfsstat: make -q work without -e/-E

### PR DESCRIPTION
**Pull request by lexiwinter**
cc @asomers

### CODE REVIEW

**Review by asomers — APPROVED** [review]
LGTM.

**Comment by lexiwinter** [comment]
should i amend this with an MFC after (like the other nfsstat change)?  it's a pretty minor fix that should be MFCable without problems, but i'm not sure what the criteria are for MFCs.

**Comment by lexiwinter** [comment]
i took the initiative and added the MFC after tag to the commit.

**Comment by emaste** [comment]
@asomers do you want to land this? I can add it to my queue if you like

**Comment by asomers** [comment]
I'll take care of it, @emaste

**Comment by asomers** [comment]
Fixed by f79b200b6aef

**Pull request closed without merging**
