### PR TITLE
bsd.prog.mk: Link with --fatal-warnings like bsd.lib.mk

### PR DESCRIPTION
**Pull request by jrtc27**
Testing cross-OS bootstrapping

### CODE REVIEW

**Review by emaste — APPROVED** [review]

**Comment by emaste** [comment]
We currently have `LD_FATAL_WARNINGS=no` in:
- lib/libbsnmp/libbsnmp/Makefile
- usr.sbin/nmtree/Makefile

The second is curious, if nothing handled it in bsd.prog.mk anyway. It was added in c4bd82d701879

**Comment by jrtc27** [comment]
Yeah, that was upstreamed from CheriBSD without noticing that it didn’t do anything in FreeBSD

**Comment by bsdimp** [comment]
Looks good to me as well

**Comment by jrtc27** [comment]
Oh it's pretty simple, LLD still doesn't bother to implement this feature... https://github.com/llvm/llvm-project/issues/41353 *sigh*

**Comment by emaste** [comment]
What are the warnings we get with amd64-gcc12?

**Comment by jrtc27** [comment]
Cirrus CI amd64-gcc12 died with:

> /usr/local/bin/x86_64-unknown-freebsd13.1-ld: dlopen_empty_test.o: in function `atfu_dlopen_empty_test_body':
> /tmp/cirrus-ci-build/lib/libc/tests/gen/dlopen_empty_test.c:66: warning: warning: mktemp() possibly used unsafely; consider using mkstemp()

I'm doing a build locally with amd64-gcc12 to see if there are any others past that.

**Comment by bsdimp** [comment]
So what's the status here? Seems like this should just be closed since it was a testing PR, but maybe I'm missing something

**Comment by jrtc27** [comment]
I need to get back to the patch in the new year; a bunch of tests have warnings due to uses of deprecated functions; some intentional that need suppressing, others just old crusty code that is better to rewrite.

**Comment by jrtc27** [comment]
That is I eventually intend to update the branch and thus testing PR

**Comment by bsdimp** [comment]
Ok marking in progress until then...

**Comment by bsdimp** [comment]
@jrtc27 any status update?

**Comment by jrtc27** [comment]
> @jrtc27 any status update?

Not yet, but I'm starting to drain my backlog of TODOs, as you may have seen from my recent revivals of old patch series.

**Comment by bsdimp** [comment]
> > @jrtc27 any status update?
> 
> Not yet, but I'm starting to drain my backlog of TODOs, as you may have seen from my recent revivals of old patch series.

Can we close this pull request?

**Comment by bsdimp** [comment]
I'm cleaning up the pull requests... I'm going to close it. You can resubmit or reopen when you have time.

**Pull request closed without merging**
