### PR TITLE
Add support for Intel Atom S1200 UART

### PR DESCRIPTION
**Pull request by hhartzer**
PR: 278316

Signed-off-by: Henrich Hartzer <henrichhartzer@tuta.io>

### CODE REVIEW

**Comment by hhartzer** [comment]
This did not work until I disabled MSI. If this looks good, I would appreciate it if it could be backported to stable/14.

Thank you!

**Comment by bsdimp** [comment]
Ideally, we'd want to know *WHY* it didn't work with MSI enabled. Did you discover any erratum or other basis for disabling msi?

**Comment by hhartzer** [comment]
It just didn't work for me with MSI enabled. I could either disable MSI or set `debug.uart_force_poll` to `1` to get it going. There were no BIOS options around this.

I imagine this isn't going to be used very commonly. I do think it's not going to hurt much, performance wise, for the typical applications to not use MSI.

There is only one other driver in there that doesn't use MSI.

I do agree that ideally this would be better understood, and if someone else has the same kind of hardware I'd encourage them to test and I'd be happy to check patches on my hardware as well. I've already put several hours into this, (largely because I've never worked around this before) so I'd prefer not to test a whole lot other permutations unless they're straight forward.

**Comment by bsdimp** [comment]
Great! Wished for better, but that's enough

**Comment by bsdimp** [comment]
Thanks for the explanation and contribution. Landed.

**Comment by hhartzer** [comment]
Thank you so much!! I appreciate you merging this!

Might it be possible to backport this to stable/14? It'd be nice if I could use it in 14.1, when it comes in a few months, without recompiling.

**Comment by bsdimp** [comment]
Queued to my mfc queue. I'll push it in Monday or Tuesday.

**Pull request closed without merging**
