### PR TITLE
share/examples/sound/midi.c, share/examples/sound/ossmidi.h typo

### PR DESCRIPTION
**Pull request by Assume-Zhan**
- Name: Assume-Zhan
- Email: [assume0701@gapp.nthu.edu.tw](mailto:assume0701@gapp.nthu.edu.tw)

Typo in line 52 of share/examples/sound/midi.c: CONTROLER_ON -> CONTROLLER_ON
Typo in line 68 of share/examples/sound/midi.c: CONTROLER_ON -> CONTROLLER_ON
Typo in line 36 of share/examples/sound/ossmidi.h: CONTROLER_ON -> CONTROLLER_ON

Event: This is from the Advanced UNIX Programming Course (Fall’23) at NTHU.

### CODE REVIEW

**Comment by lwhsu** [comment]
The name and email you provided in the comment are different from what's in https://patch-diff.githubusercontent.com/raw/freebsd/freebsd-src/pull/994.patch , which is your preference?

**Comment by Assume-Zhan** [comment]
Sorry about that, I prefer use the name and email below:
- Name: Assume-Zhan
- Email: [assume0701@gapp.nthu.edu.tw](mailto:assume0701@gapp.nthu.edu.tw)

**Comment by lwhsu** [comment]
Ok, then please amend your commit (`git commit --amend`) and do a force push to update the commit in this PR. While doing so, please also update the commit message to a more descriptive one, in the subject and body, and with

```
Event: Advanced UNIX Programming Course (Fall’23) at NTHU.
```

In the bottom of the commit message.

**Review by lwhsu — APPROVED** [review]

**Comment by lwhsu** [comment]
Merged as 0789c3bd2c4597e40b1d2556d21bfd10ff628a0a

**Pull request closed without merging**
