### PR TITLE
Save an instruction in locore.S

### PR DESCRIPTION
**Pull request by AtariDreams**
We can move and sub at the same time, so let's do that.

### CODE REVIEW

**Review by kevans91 — APPROVED** [review]
This LGTM; let's tag @zxombie for a second opinion -- the one instruction won't make much of a difference, but I think it could be considered better style at least and slightly more clear in intent.

**Comment by AtariDreams** [comment]
@bsdimp Could you please merge this?

**Comment by bsdimp** [comment]
@emaste
Author: Alfonso Gregory <gfunni234@gmail.com>
is the author that we've used for @AtariDreams other commits

**Comment by AtariDreams** [comment]
Fixed @bsdimp @kevans91

**Comment by emaste** [comment]
Oops sorry @kevans91 I missed your reviewed-by when pushing this. Anyhow, it's in now, in 79cfcc681954069652f08d13dbe9cb3c023d9d33. @AtariDreams thanks for the patch!

**Comment by emaste** [comment]
Oops, did not actually push the commit -- done now in e1fe34707a60b0f6cf47397c6eea0a39d675e3ac (and added @kevans91 as a reviewer)

**Pull request closed without merging**
