### PR TITLE
Improve various disk-related manual pages

### PR DESCRIPTION
**Pull request by tomhukins**

### CODE REVIEW

**Comment by bsdimp** [comment]
Looks great to me conceptually, maybe a doc person should look at the details.

**Comment by grahamperrin** [comment]
Partly related: FreeBSD bug [264387 – geom(4) should mention geom(8)](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264387), flagged for feedback from `geom@`. 

Additionally, I'll flag for feedback from `doc@` (already a cc recipient); reading this type of markup is not my forte.

**Comment by grahamperrin** [comment]
From ceri@ at <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264387#c3>: 

> Yes on behalf of doc@

**Comment by bsdimp** [comment]
Landed as 409594ef340b

**Pull request closed without merging**
