### PR TITLE
hier(7): fix inline markup for a variable

### PR DESCRIPTION
**Pull request by grahamperrin**
Fixes: 6469f9c595c6 hier(7): improvement, modernisation

### CODE REVIEW

**Comment by bsdimp** [comment]
So do you want to use your gmail address or your FreeBSD address to land this?
Otherwise I approve.

**Comment by bsdimp** [comment]
Tagging with changes-required, though if it's totally correct just let me know.

**Comment by grahamperrin** [comment]
> your gmail address or your FreeBSD address

`@FreeBSD.org`, I'll commit, thanks. 

As 6469f9c related to bug <https://bugs.freebsd.org/261349>, so should this fix also have `261349` in a `PR` line? As I did with 5ca7f02

**Comment by bsdimp** [comment]
Yes. Please do add a PR line. And update the author to your FreeBSD address while you're ad it.

**Review by mhorne — APPROVED** [review]

**Comment by grahamperrin** [comment]
Closed by <https://github.com/freebsd/freebsd-src/commit/b374a3921d97bdb20b103aaeb91988c3d355ea71>.

----

Seeing PR whilst drafting the commit message, thinking _pull request_, I omitted the second PR line (for 784). Sorry.

**Pull request closed without merging**
